import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { CanonicalEventConsumerRegistry, CanonicalEventDispatcher, DigitalTwinImpactConsumer } from '../src/canonical-events.js';

test('every material timeline event automatically enters the canonical object event ledger',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository,()=> '2026-07-10T12:00:00.000Z');const workspace=await service.createWorkspace({name:'Aware Firm'});const matter=await service.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Matter'});const task=await service.createObject(workspace.id,{parentObjectId:matter.id,dimension:'operation',type:'task',title:'Review'});const seen=[];const consumers=new CanonicalEventConsumerRegistry().register('digital-twin-impact',{async handle(event){seen.push(event);}});const result=await new CanonicalEventDispatcher(repository,consumers).dispatchPending();assert.equal(result.completed,2);const taskEvent=seen.find((event)=>event.affectedObjectIds.includes(task.id));assert.ok(taskEvent);assert.equal(taskEvent.correlationId,taskEvent.id);});

test('canonical event delivery is idempotent per consumer and replayable for a new consumer',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository);const workspace=await service.createWorkspace({name:'Replay Firm'});await service.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Matter'});let first=0;const registry=new CanonicalEventConsumerRegistry().register('consumer-a',{async handle(){first+=1;}});const dispatcher=new CanonicalEventDispatcher(repository,registry);await dispatcher.dispatchPending();await dispatcher.dispatchPending();assert.equal(first,1);let replay=0;await new CanonicalEventDispatcher(repository,new CanonicalEventConsumerRegistry().register('consumer-b',{async handle(){replay+=1;}})).dispatchPending();assert.equal(replay,1);});

test('repeated consumer failures move delivery to dead letter without corrupting canonical events',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository);const workspace=await service.createWorkspace({name:'Failure Firm'});await service.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Matter'});let attempts=0;const dispatcher=new CanonicalEventDispatcher(repository,new CanonicalEventConsumerRegistry().register('failing',{async handle(){attempts+=1;throw new Error('failure');}}),{maxAttempts:2});assert.deepEqual(await dispatcher.dispatchPending(),{completed:0,failed:1});assert.deepEqual(await dispatcher.dispatchPending(),{completed:0,failed:1});assert.deepEqual(await dispatcher.dispatchPending(),{completed:0,failed:0});assert.equal(attempts,2);});

test('material events reject affected objects outside their workspace',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository);const first=await service.createWorkspace({name:'First'});const second=await service.createWorkspace({name:'Second'});const foreign=await service.createObject(second.id,{dimension:'matter',type:'civil',title:'Foreign'});await assert.rejects(()=>service.createEvent(first.id,{type:'test',actorId:'system',source:'test',relatedObjectIds:[foreign.id]}),(error)=>error.code==='OBJECT_NOT_FOUND');});

test('canonical events propagate situational reanalysis to connected graph objects exactly once',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository,()=> '2026-07-10T12:00:00.000Z');const workspace=await service.createWorkspace({name:'Twin Firm'});const matter=await service.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Matter'});const evidence=await service.createObject(workspace.id,{dimension:'evidence',type:'report',title:'Report'});await service.createRelationship(workspace.id,{fromObjectId:evidence.id,toObjectId:matter.id,type:'supports'});const event=await service.createEvent(workspace.id,{parentObjectId:evidence.id,type:'evidence.updated',actorId:'usr_1',source:'atlas'});const consumer=new DigitalTwinImpactConsumer(repository,()=> '2026-07-10T12:01:00.000Z');assert.deepEqual(await consumer.handle({id:event.id,workspaceId:workspace.id,correlationId:event.id,affectedObjectIds:[evidence.id]}),{queued:1});assert.deepEqual(await consumer.handle({id:event.id,workspaceId:workspace.id,correlationId:event.id,affectedObjectIds:[evidence.id]}),{queued:0});const jobs=await repository.listIntelligenceJobs(workspace.id);const impact=jobs.find((job)=>job.triggerType==='graph.impact'&&job.objectId===matter.id);assert.ok(impact);assert.deepEqual(impact.payload.sourceObjectIds,[evidence.id]);});

test('relationship mutations publish both connected canonical objects as affected',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository);const workspace=await service.createWorkspace({name:'Graph Firm'});const first=await service.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Matter'});const second=await service.createObject(workspace.id,{dimension:'evidence',type:'report',title:'Report'});await service.createRelationship(workspace.id,{fromObjectId:second.id,toObjectId:first.id,type:'supports'});const events=[];await new CanonicalEventDispatcher(repository,new CanonicalEventConsumerRegistry().register('audit',{async handle(event){events.push(event);}})).dispatchPending();const relationshipEvent=events.find((event)=>event.eventType==='relationship.created');assert.deepEqual(new Set(relationshipEvent.affectedObjectIds),new Set([first.id,second.id]));});
