import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';

test('new cases are screened against party names throughout the authorized firm twin',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository,()=> '2026-07-14T14:00:00.000Z');const firm=await service.createWorkspace({name:'Conflict Firm'});const first=await service.createObject(firm.id,{dimension:'matter',type:'civil',title:'Morgan v. Lakeside Property Group',state:{status:'open',parties:[{name:'Taylor Morgan',role:'client'},{name:'Lakeside Property Group',role:'opposing party'}]}});await service.createObject(firm.id,{parentObjectId:first.id,dimension:'organization',type:'opposing_party',title:'Lakeside Property Group',state:{matterId:first.id}});const second=await service.createObject(firm.id,{dimension:'matter',type:'insurance',title:'Harbor Insurance v. Lakeside Property Group',state:{status:'open',parties:['Harbor Insurance','Lakeside Property Group']}});const result=await service.conflictAlerts(firm.id);const alert=result.alerts.find(item=>item.matterId===second.id&&item.partyName==='Lakeside Property Group');assert.ok(alert);assert.equal(alert.status,'potential_match');assert.equal(alert.requiresAttorneyReview,true);assert.equal(alert.confidence,1);assert.ok(alert.matches.some(match=>match.matterId===first.id));assert.equal(result.method.engine,'native-digital-twin');assert.equal(result.method.modelRequired,false);assert.equal(result.method.humanDecisionRequired,true);});

test('conflict screening extracts caption parties and never crosses firm boundaries',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository);const first=await service.createWorkspace({name:'First Firm'});const second=await service.createWorkspace({name:'Second Firm'});await service.createObject(second.id,{dimension:'matter',type:'civil',title:'Jordan Reed v. Northline Holdings',state:{status:'open'}});const local=await service.createObject(first.id,{dimension:'matter',type:'civil',title:'Jordan Reed v. Local Company',state:{status:'open'}});const result=await service.conflictAlerts(first.id);assert.equal(result.matterCount,1);assert.equal(result.partyCount,2);assert.equal(result.alerts.some(alert=>alert.matterId===local.id&&alert.partyName==='Jordan Reed'),false);});

test('matching names inside the same case do not create a false conflict alert',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository);const firm=await service.createWorkspace({name:'Single Case Firm'});const matter=await service.createObject(firm.id,{dimension:'matter',type:'civil',title:'Taylor Morgan v. Acme LLC',state:{status:'open',clientName:'Taylor Morgan',parties:['Taylor Morgan','Acme LLC']}});await service.createObject(firm.id,{parentObjectId:matter.id,dimension:'client',type:'client',title:'Taylor Morgan',state:{matterId:matter.id}});const result=await service.conflictAlerts(firm.id);assert.equal(result.alertCount,0);});
