import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { AccountingService, ProviderRegistry } from '../src/accounting.js';
import { EvmTokenPaymentProvider } from '../src/crypto-provider-adapters.js';

const wallet='0x1111111111111111111111111111111111111111';
const token='0x2222222222222222222222222222222222222222';
const tx='0x'+'a'.repeat(64);

function fakeProvider(status='confirmed'){
  return {describe:()=>({kind:'direct_wallet',asset:'USDC',network:'base',chainId:8453,decimals:6,requiredConfirmations:12,custody:false}),validateAddress:value=>value.toLowerCase(),quote:({amountMinor,currency})=>({asset:'USDC',network:'base',chainId:8453,tokenAddress:token,decimals:6,units:String(BigInt(amountMinor)*10000n),fiatAmountMinor:amountMinor,currency}),instruction:({destinationAddress,quote})=>({destinationAddress,paymentUri:`ethereum:${token}@8453/transfer?address=${destinationAddress}&uint256=${quote.units}`}),verifyTransaction:async()=>({status,transactionHash:tx,confirmations:12,blockNumber:100,receivedUnits:'5000000000',asset:'USDC',network:'base',tokenAddress:token})};
}

async function fixture(options={}){const repository=new InMemoryRepository();const atlas=new AtlasService(repository);const workspace=await atlas.createWorkspace({name:'Crypto Firm'});const matter=await atlas.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Morgan v. Lakeside'});const client=await atlas.createObject(workspace.id,{parentObjectId:matter.id,dimension:'client',type:'client',title:'Taylor Morgan',state:{matterId:matter.id}});return {repository,atlas,workspace,matter,client,accounting:new AccountingService(atlas,options)};}

test('EVM token adapter verifies contract destination amount and confirmation depth through JSON-RPC',async()=>{const calls=[];const transport=async(_url,options)=>{const body=JSON.parse(options.body);calls.push(body.method);const result=body.method==='eth_getTransactionReceipt'?{status:'0x1',blockNumber:'0x64',logs:[{address:token,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef','0x'+'0'.repeat(64),'0x'+'0'.repeat(24)+wallet.slice(2)],data:'0x4c4b40'}]}:'0x70';return {ok:true,json:async()=>({jsonrpc:'2.0',id:body.id,result})};};const provider=new EvmTokenPaymentProvider({rpcUrl:'https://rpc.example',network:'base',chainId:8453,tokenAddress:token,transport,confirmations:12});const quote=provider.quote({amountMinor:500,currency:'USD'});assert.equal(quote.units,'5000000');const verified=await provider.verifyTransaction({transactionHash:tx,destinationAddress:wallet,expectedUnits:quote.units});assert.equal(verified.status,'confirmed');assert.equal(verified.confirmations,13);assert.deepEqual(calls,['eth_getTransactionReceipt','eth_blockNumber']);});

test('law firm crypto payment is tied to its invoice and only booked after chain confirmation',async()=>{const cryptoProviders=new ProviderRegistry('Crypto payment').register('base-usdc',fakeProvider());const {accounting,workspace,matter,client}=await fixture({cryptoProviders});const invoice=await accounting.createInvoice(workspace.id,{matterId:matter.id,clientId:client.id,title:'Retainer',amountMinor:500_000},'usr_owner');const account=await accounting.createCryptoReceivingAccount(workspace.id,{provider:'base-usdc',address:wallet},'usr_owner');const request=await accounting.createInvoiceCryptoRequest(workspace.id,{invoiceId:invoice.id,receivingAccountId:account.id},'usr_owner');assert.equal(request.state.custody,false);assert.match(request.state.paymentUri,/ethereum:/);const confirmed=await accounting.confirmCryptoPayment(workspace.id,{paymentRequestId:request.id,transactionHash:tx},'usr_owner');assert.equal(confirmed.payment.state.rail,'crypto');assert.equal(confirmed.payment.state.transactionHash,tx);assert.equal((await accounting.summary(workspace.id)).receivableMinor,0);const duplicate=await accounting.confirmCryptoPayment(workspace.id,{paymentRequestId:request.id,transactionHash:tx},'usr_owner');assert.equal(duplicate.duplicate,true);});

test('pending blockchain confirmations never create a payment',async()=>{const cryptoProviders=new ProviderRegistry('Crypto payment').register('base-usdc',fakeProvider('pending'));const {accounting,workspace,matter}=await fixture({cryptoProviders});const invoice=await accounting.createInvoice(workspace.id,{matterId:matter.id,title:'Fees',amountMinor:10_000},'usr_owner');const account=await accounting.createCryptoReceivingAccount(workspace.id,{provider:'base-usdc',address:wallet},'usr_owner');const request=await accounting.createInvoiceCryptoRequest(workspace.id,{invoiceId:invoice.id,receivingAccountId:account.id},'usr_owner');const result=await accounting.confirmCryptoPayment(workspace.id,{paymentRequestId:request.id,transactionHash:tx},'usr_owner');assert.equal(result.status,'pending');assert.equal(result.payment,null);assert.equal((await accounting.summary(workspace.id)).paidMinor,0);});

test('Atlas subscription crypto requests use server-side plan pricing and activate only after confirmation',async()=>{const cryptoProviders=new ProviderRegistry('Crypto payment').register('base-usdc',fakeProvider());const {accounting,workspace,repository}=await fixture({cryptoProviders,subscriptionPrices:{pilot:19_900},platformCryptoAccount:{provider:'base-usdc',address:wallet}});const request=await accounting.createSubscriptionCryptoRequest(workspace.id,{},'usr_owner');assert.equal(request.state.amountMinor,19_900);assert.equal(request.state.purpose,'atlas_subscription');const result=await accounting.confirmCryptoPayment(workspace.id,{paymentRequestId:request.id,transactionHash:tx},'usr_owner');assert.equal(result.payment.type,'subscription_payment');assert.equal((await repository.getSubscription(workspace.id)).status,'active');});

test('generic external-payment recording cannot bypass blockchain confirmation',async()=>{const {accounting,workspace,matter}=await fixture();const invoice=await accounting.createInvoice(workspace.id,{matterId:matter.id,title:'Fees',amountMinor:10_000},'usr_owner');await assert.rejects(()=>accounting.recordExternalPayment(workspace.id,{invoiceId:invoice.id,rail:'crypto',amountMinor:10_000,externalReference:tx},'usr_owner'),/blockchain verification/);});
