import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { createHash } from 'node:crypto';
import { DocumentChunkIndexer, DocumentKnowledgeIndexer, runDocumentKnowledgeBackfill } from '../src/document-knowledge.js';
import { RepositoryBlobStore } from '../src/file-storage.js';
import { AesGcmContentCipher, isEncryptedContent } from '../src/content-security.js';

async function fixture(){const repository=new InMemoryRepository();const service=new AtlasService(repository,()=> '2026-07-13T16:00:00.000Z');const one=await service.createWorkspace({name:'Firm One'});const two=await service.createWorkspace({name:'Firm Two'});const documentOne=await service.createObject(one.id,{dimension:'document',type:'order',title:'Production Order'});const documentTwo=await service.createObject(two.id,{dimension:'document',type:'notice',title:'Hearing Notice'});for(const value of [{id:'ino_one',workspaceId:one.id,sourceObjectId:documentOne.id,status:'accepted',data:{title:'Produce records'},kind:'duty'},{id:'ino_rejected',workspaceId:one.id,sourceObjectId:documentOne.id,status:'rejected',data:{title:'Invented duty'},kind:'duty'},{id:'ino_two',workspaceId:two.id,sourceObjectId:documentTwo.id,status:'candidate',data:{title:'Attend hearing'},kind:'deadline'}])await repository.createIntelligenceObservation({...value,jobId:'inj_test',confidence:.9,sourceLocation:{page:2},provider:'local',reviewedBy:null,reviewedAt:null,createdAt:'2026-07-13T16:00:00.000Z'});return {repository,one,two};}

test('document knowledge backfill is firm-scoped repeat-safe and excludes rejected findings',async()=>{const {repository,one,two}=await fixture();const calls=[];const provider={embeddingModel:'semantic-test',capabilities(){return {embeddingModel:'semantic-test'};},async embedTexts(input){calls.push(input);return {vectors:input.map((_,index)=>[1,index,0]),provider:'local',model:'semantic-test',indexModel:'semantic-test',dimensions:3,usage:{inputTokens:input.length,outputTokens:0,totalTokens:input.length}};}};const indexer=new DocumentKnowledgeIndexer(repository,provider,()=> '2026-07-13T16:01:00.000Z');const first=await indexer.indexAll({limit:10});assert.equal(first.indexed,2);assert.equal((await repository.listDocumentKnowledgeEmbeddings(one.id)).length,1);assert.equal((await repository.listDocumentKnowledgeEmbeddings(two.id)).length,1);assert.equal(calls.flat().some(text=>text.includes('Invented duty')),false);const second=await indexer.indexAll({limit:10});assert.equal(second.indexed,0);assert.equal(calls.length,2);});

test('document knowledge drain completes bounded historical batches',async()=>{const {repository,one}=await fixture();const document=(await repository.listObjects(one.id,{dimension:'document'}))[0];await repository.createIntelligenceObservation({id:'ino_extra',workspaceId:one.id,jobId:'inj_test',sourceObjectId:document.id,kind:'fact',data:{title:'Second finding'},confidence:.8,sourceLocation:{page:3},provider:'local',status:'accepted',reviewedBy:null,reviewedAt:null,createdAt:'2026-07-13T16:00:01.000Z'});const provider={capabilities(){return {embeddingModel:'semantic-test'};},async embedTexts(input){return {vectors:input.map(()=>[1,0]),provider:'local',model:'semantic-test',dimensions:2};}};const result=await new DocumentKnowledgeIndexer(repository,provider).drain({limit:1,maxBatches:5});assert.equal(result.indexed,3);assert.equal(result.complete,true);assert.equal(result.batches,3);});

test('background semantic backfill stops cleanly with the intelligence worker signal',async()=>{const controller=new AbortController();let calls=0;const indexer={async indexAll(){calls+=1;controller.abort();return {indexed:0};}};await runDocumentKnowledgeBackfill(indexer,{signal:controller.signal,intervalMs:1});assert.equal(calls,1);});

test('raw document chunk indexing is encrypted firm-scoped and repeat-safe',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository,()=> '2026-07-13T17:00:00.000Z');const one=await service.createWorkspace({name:'Chunk Firm'});const two=await service.createWorkspace({name:'Other Firm'});const bytes=Buffer.from('Discovery responses must be served by July 24.');const sha256=createHash('sha256').update(bytes).digest('hex');await repository.createDocumentBlob(one.id,sha256,bytes,'2026-07-13T17:00:00.000Z');const document=await service.createObject(one.id,{dimension:'document',type:'discovery',title:'Discovery Order',state:{storageRef:`atlas-blob://${one.id}/${sha256}`,size:bytes.length,sha256,mediaType:'application/pdf'}});const provider={capabilities(){return {embeddingModel:'chunk-test'};},async extractDocumentChunks(){return {retrievalChunks:[{text:'Discovery responses must be served by July 24.',sourceLocation:{page:4,section:'Response deadline'}}],provider:'local'};},async embedTexts(input){return {vectors:input.map(()=>[1,0,0]),provider:'local',model:'chunk-test',indexModel:'chunk-test',dimensions:3};}};const key=Buffer.alloc(32,7).toString('base64');const cipher=new AesGcmContentCipher({keys:{active:key},activeKeyId:'active'});const indexer=new DocumentChunkIndexer(repository,provider,new RepositoryBlobStore(repository),cipher,()=> '2026-07-13T17:01:00.000Z');assert.equal((await indexer.indexAll()).indexed,1);const chunks=await repository.listDocumentKnowledgeChunks(one.id,'chunk-test');assert.equal(chunks.length,1);assert.equal(chunks[0].sourceObjectId,document.id);assert.equal(isEncryptedContent(chunks[0].content),true);assert.equal(chunks[0].content.includes('Discovery responses'),false);assert.equal(cipher.decrypt(chunks[0].content,`document-chunk:${chunks[0].id}:content`),'Discovery responses must be served by July 24.');assert.equal((await repository.listDocumentKnowledgeChunks(two.id,'chunk-test')).length,0);assert.equal((await indexer.indexAll()).indexed,0);});
