import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { ContractedLegalResearchApiProvider, LegalResearchProviderRegistry, LegalResearchService } from '../src/legal-research.js';
import { AtlasAssistant, AtlasToolRegistry } from '../src/assistant.js';

const response=(body,status=200)=>({ok:status>=200&&status<300,status,async json(){return body;}});

test('contracted legal research exchanges OAuth credentials and normalizes cited results',async()=>{const calls=[];const transport=async(url,options)=>{calls.push({url,options});if(url.endsWith('/token'))return response({access_token:'licensed-token',expires_in:600});return response({answer:'Rule 26 requires proportional discovery.',results:[{title:'Federal Rule of Civil Procedure 26',citation:'Fed. R. Civ. P. 26',url:'https://research.example/rule-26',court:'Federal',treatment:'Good law'}]});};const provider=new ContractedLegalResearchApiProvider({name:'lexisnexis',clientId:'id',clientSecret:'secret',tokenEndpoint:'https://api.example/token',searchEndpoint:'https://api.example/search',transport});const result=await provider.search({query:'discovery proportionality',jurisdiction:'Federal',practiceArea:'Civil litigation',limit:10});assert.equal(result.citations[0].citation,'Fed. R. Civ. P. 26');assert.match(calls[0].options.headers.authorization,/^Basic /);assert.equal(calls[1].options.headers.authorization,'Bearer licensed-token');assert.deepEqual(JSON.parse(calls[1].options.body),{query:'discovery proportionality',jurisdiction:'Federal',practiceArea:'Civil litigation',limit:10});});

test('Westlaw and LexisNexis results become one canonical case-owned research record',async()=>{const atlas=new AtlasService(new InMemoryRepository(),()=> '2026-07-14T18:00:00.000Z');const workspace=await atlas.createWorkspace({name:'Research Firm'});const matter=await atlas.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Reed v. Northline'});const providers=new LegalResearchProviderRegistry();for(const name of ['westlaw','lexisnexis'])providers.register(name,{capabilities(){return {search:true,citations:true};},async search(){return {provider:name,answer:`${name} answer`,citations:[{title:`${name} case`,citation:'123 A.3d 456',url:`https://${name}.example/case`,court:'Delaware Supreme Court',date:'2025-01-01',treatment:'Cited',summary:'Relevant holding.'}]};}});const legalResearch=new LegalResearchService(atlas,providers,()=> '2026-07-14T18:00:00.000Z');const result=await legalResearch.search(workspace.id,{provider:'all',matterId:matter.id,query:'What is the standard for compelling discovery?',jurisdiction:'Delaware'},'usr_attorney');assert.equal(result.citations.length,2);assert.equal(result.research.parentObjectId,matter.id);assert.equal(result.research.type,'legal_research');assert.deepEqual(result.research.state.providers,['westlaw','lexisnexis']);assert.equal((await atlas.getCanonicalContext(workspace.id,matter.id)).objects.some(item=>item.id===result.research.id),true);assert.equal((await atlas.listEvents(workspace.id,result.research.id)).some(event=>event.type==='object.created'),true);});

test('licensed legal research fails honestly when no contracted provider is configured',async()=>{const atlas=new AtlasService(new InMemoryRepository());const workspace=await atlas.createWorkspace({name:'Research Firm'});const legalResearch=new LegalResearchService(atlas);assert.deepEqual(legalResearch.listProviders().map(item=>[item.name,item.configured]),[['westlaw',false],['lexisnexis',false]]);await assert.rejects(()=>legalResearch.search(workspace.id,{provider:'all',query:'current legal standard'}),error=>error.code==='LEGAL_RESEARCH_PROVIDER_NOT_CONFIGURED');});

test('native AI gains one licensed-research capability without provider-specific core code',async()=>{const atlas=new AtlasService(new InMemoryRepository());const workspace=await atlas.createWorkspace({name:'AI Research Firm'});let actor;const legalResearch={listProviders(){return[{name:'westlaw',configured:true}];},async search(workspaceId,input,userId){actor=userId;const research=await atlas.createObject(workspaceId,{dimension:'operation',type:'legal_research',title:'Research',state:{query:input.query}});return {research,citations:[{provider:'westlaw',title:'Case',citation:'1 A.3d 2',url:'https://research.example/case'}],providerResults:[]};}};const tools=new AtlasToolRegistry(atlas,{legalResearch});assert.equal(tools.definitions().some(item=>item.name==='search_licensed_legal_research'),true);const result=await tools.execute('search_licensed_legal_research',workspace.id,{query:'controlling standard'},{userId:'usr_attorney'});assert.equal(actor,'usr_attorney');assert.equal(result.sources.some(item=>item.sourceType==='licensed_legal_research'),true);});

test('conversational legal research requires live citations and saves its synthesis into canonical case context',async()=>{const atlas=new AtlasService(new InMemoryRepository(),()=> '2026-07-14T20:00:00.000Z');const workspace=await atlas.createWorkspace({name:'Live Research Firm'});const matter=await atlas.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Fictional Matter'});const webResearch={async search(){return {answer:'Current public authority located.',sources:[{title:'Federal Rules of Civil Procedure',url:'https://www.uscourts.gov/rules-policies/current-rules-practice-procedure'}]};}};let round=0;let developerContext='';const model={async complete(input){developerContext=input.messages.filter(item=>item.role==='developer').map(item=>item.content).join('\n');if(round++===0)return {toolCalls:[{id:'call_web',name:'search_public_web',arguments:{query:'current federal discovery proportionality standard'}}],usage:{}};return {text:'Rule 26(b)(1) governs proportionality. Validate the text, authorities, and current treatment before reliance.',usage:{}};}};const assistant=new AtlasAssistant(model,new AtlasToolRegistry(atlas,{webResearch}),{clock:()=> '2026-07-14T20:00:00.000Z'});const result=await assistant.research({workspaceId:workspace.id,userId:'usr_attorney',matterId:matter.id,sourceMode:'best_available',jurisdiction:'Federal',prompt:'What is the current proportionality standard?'});assert.equal(result.webSources.length,1);assert.equal(result.research.type,'legal_research_analysis');assert.equal(result.research.parentObjectId,matter.id);assert.equal(result.research.state.requiresAttorneyValidation,true);assert.equal(result.research.state.citations[0].provider,'public_web');assert.match(developerContext,/Conduct source-grounded legal research rather than answering from memory/);assert.equal((await atlas.getCanonicalContext(workspace.id,matter.id)).objects.some(item=>item.id===result.research.id),true);});

test('firm-wide legal research prepares a research-backed motion template in Workspace without requiring a matterId',async()=>{const repository=new InMemoryRepository();const clock=()=> '2026-07-14T20:15:00.000Z';const atlas=new AtlasService(repository,clock);const workspace=await atlas.createWorkspace({name:'DUI Research Firm'});const webResearch={async search(input){assert.match(input.query,/DUI/i);return {answer:'Current DUI authority located.',sources:[{title:'Official state appellate decisions',url:'https://courts.example.gov/opinions/dui'}]};}};let round=0;let developerContext='';const model={async complete(input){developerContext=input.messages.filter(item=>item.role==='developer').map(item=>item.content).join('\n');if(round++===0)return {toolCalls:[{id:'call_web',name:'search_public_web',arguments:{query:'current state DUI suppression case law official appellate decisions'}}],usage:{}};if(round===2)return {toolCalls:[{id:'call_draft',name:'propose_create_legal_document',arguments:{documentType:'motion',title:'DUI suppression motion working template',body:'MOTION TO SUPPRESS\n\nThe attorney must validate the cited DUI authorities and insert supported facts before use.'}}],usage:{}};return {text:'I researched current DUI authority and prepared a generic motion template in Workspace for attorney review.',usage:{}};}};const assistant=new AtlasAssistant(model,new AtlasToolRegistry(atlas,{webResearch}),{repository,clock});const result=await assistant.research({workspaceId:workspace.id,userId:'usr_attorney',sourceMode:'best_available',jurisdiction:'State courts',prompt:'Pull current DUI case law and generate a template motion using it.'});assert.equal(result.research.parentObjectId,null);assert.equal(result.actionProposals.length,1);assert.equal(result.actionProposals[0].input.matterId,null);assert.equal(result.actionProposals[0].input.generationProvenance.kind,'atlas_generic_legal_template');assert.match(result.actionProposals[0].input.content,/ATTORNEY INPUT REQUIRED: COURT/);assert.deepEqual(result.research.state.proposedActionIds,[result.actionProposals[0].id]);const context=await atlas.getCanonicalContext(workspace.id,result.research.id);assert.equal(context.intelligence.actions.some(action=>action.id===result.actionProposals[0].id),true);assert.equal((await atlas.listAiActionProposals(workspace.id,'pending'))[0].id,result.actionProposals[0].id);assert.match(developerContext,/matterId is not required/);assert.match(developerContext,/unified Workspace/);});

test('conversational legal research fails honestly when no live research path is configured',async()=>{const atlas=new AtlasService(new InMemoryRepository());const workspace=await atlas.createWorkspace({name:'Offline Research Firm'});const assistant=new AtlasAssistant({async complete(){throw new Error('must not run');}},new AtlasToolRegistry(atlas));assert.equal(assistant.legalResearchCapabilities().liveAvailable,false);await assert.rejects(()=>assistant.research({workspaceId:workspace.id,userId:'usr_attorney',prompt:'Research the current controlling standard'}),error=>error.code==='LEGAL_RESEARCH_LIVE_SOURCE_UNAVAILABLE');});
