import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { ProviderRegistry } from '../src/accounting.js';
import { HttpAggregatePublicSource, MarketingService } from '../src/marketing.js';

const clock=()=> '2026-07-14T16:00:00.000Z';

test('aggregate public events become canonical marketing signals without named leads',async()=>{const atlas=new AtlasService(new InMemoryRepository(),clock);const workspace=await atlas.createWorkspace({name:'Marketing Firm'});const publicSources=new ProviderRegistry('Marketing public data').register('official-arrests',{describe(){return{label:'Official arrest totals',eventType:'arrests',aggregateOnly:true,personLevelUse:false};},async fetchTrends(){return[{count:12,observedAt:'2026-07-13T00:00:00.000Z',jurisdiction:'Example County, DE',sourceUrl:'https://data.example.gov/arrests',sourceName:'Official arrest totals'}];}}).register('official-crashes',{describe(){return{label:'Official crash totals',eventType:'car_accidents',aggregateOnly:true,personLevelUse:false};},async fetchTrends(){return[{count:7,observedAt:'2026-07-13T00:00:00.000Z',jurisdiction:'Example County, DE',sourceUrl:'https://data.example.gov/crashes',sourceName:'Official crash totals'}];}});const marketing=new MarketingService(atlas,{publicSources,clock});const result=await marketing.scan(workspace.id,{eventTypes:['arrests','dissolution_petitions','car_accidents'],jurisdiction:'Example County, DE',from:'2026-07-01',to:'2026-07-14'},'usr_attorney');assert.equal(result.signals.length,2);assert.deepEqual(result.missingEventTypes,['dissolution_petitions']);assert.equal(result.signals.every(item=>item.state.aggregateOnly&&item.state.personalRecordsStored===false),true);assert.equal(JSON.stringify(result).includes('defendant'),false);const status=await marketing.status(workspace.id);assert.equal(status.sourceCatalog.find(item=>item.eventType==='arrests').configured,true);assert.equal(status.sourceCatalog.find(item=>item.eventType==='dissolution_petitions').configured,false);});

test('campaigns use broad geographic audiences and reach connected providers only as paused drafts',async()=>{const atlas=new AtlasService(new InMemoryRepository(),clock);const workspace=await atlas.createWorkspace({name:'Campaign Firm'});const adCalls=[];const adProviders=new ProviderRegistry('Advertising').register('meta',{availableFor(workspaceId){return workspaceId===workspace.id;},describe(){return{label:'Meta Ads',channels:['facebook','instagram'],connected:true,createsPaused:true};},async createPausedCampaign(input){adCalls.push(input);return{externalId:'meta_123',managementUrl:'https://business.facebook.com/adsmanager/manage/campaigns'};}});const marketing=new MarketingService(atlas,{adProviders,clock});const campaign=await marketing.createCampaign(workspace.id,{title:'General criminal defense awareness',practiceArea:'Criminal defense',channels:['facebook','instagram'],budgetMinor:50000,startAt:'2026-07-20',endAt:'2026-08-20',geography:'Example County, Delaware',radiusMiles:25,headline:'Understand your legal options',body:'General information about the criminal process. No attorney-client relationship is formed.',landingPage:'https://firm.example/criminal-defense'},'usr_attorney');assert.equal(campaign.state.targeting.mode,'broad_geographic');assert.equal(campaign.state.targeting.namedPublicRecordAudience,false);assert.equal(campaign.state.externalPublishing,false);const prepared=await marketing.prepareCampaign(workspace.id,campaign.id,{attorneyAdvertisingRulesReviewed:true,platformPoliciesReviewed:true,landingPageReviewed:true},'usr_attorney');assert.equal(adCalls.length,1);assert.deepEqual(adCalls[0].channels,['facebook','instagram']);assert.equal(prepared.launches[0].state.status,'paused');assert.equal(prepared.launches[0].state.activatedByAtlas,false);assert.equal(prepared.campaign.state.status,'provider_review');});

test('marketing blocks named public-record targeting and person-level source data',async()=>{const atlas=new AtlasService(new InMemoryRepository(),clock);const workspace=await atlas.createWorkspace({name:'Safe Marketing Firm'});const marketing=new MarketingService(atlas,{clock});await assert.rejects(()=>marketing.createCampaign(workspace.id,{title:'Improper outreach',practiceArea:'Family law',channels:['facebook'],budgetMinor:10000,geography:'Example County',radiusMiles:10,headline:'Need a lawyer?',body:'Contact us.',landingPage:'https://firm.example',names:['Named petitioner']},'usr_attorney'),error=>error.code==='MARKETING_TARGETING_RESTRICTED');const source=new HttpAggregatePublicSource({name:'unsafe',label:'Unsafe source',eventType:'dissolution_petitions',endpoint:'https://data.example.gov/dissolutions',transport:async()=>({ok:true,async json(){return[{count:1,jurisdiction:'Example County',date:'2026-07-14',petitioner_name:'Private Person'}];}})});await assert.rejects(()=>source.fetchTrends({from:'2026-07-01T00:00:00.000Z',to:'2026-07-14T00:00:00.000Z',jurisdiction:'Example County'}),error=>error.code==='MARKETING_SOURCE_PERSONAL_DATA_BLOCKED');});

test('campaign provider preparation requires explicit professional and platform review',async()=>{const atlas=new AtlasService(new InMemoryRepository(),clock);const workspace=await atlas.createWorkspace({name:'Review Firm'});const adProviders=new ProviderRegistry('Advertising').register('google',{availableFor(workspaceId){return workspaceId===workspace.id;},describe(){return{label:'Google Ads',channels:['google'],connected:true};},async createPausedCampaign(){return{externalId:'g_1'};}});const marketing=new MarketingService(atlas,{adProviders,clock});const campaign=await marketing.createCampaign(workspace.id,{title:'General injury law information',practiceArea:'Personal injury',channels:['google'],budgetMinor:20000,geography:'Delaware',radiusMiles:25,headline:'Learn about injury claims',body:'General legal information.',landingPage:'https://firm.example/injury'},'usr_attorney');await assert.rejects(()=>marketing.prepareCampaign(workspace.id,campaign.id,{attorneyAdvertisingRulesReviewed:true,platformPoliciesReviewed:false,landingPageReviewed:true},'usr_attorney'),error=>error.code==='MARKETING_REVIEW_REQUIRED');});

test('advertising accounts cannot be reused across firm workspaces',async()=>{const atlas=new AtlasService(new InMemoryRepository(),clock);const first=await atlas.createWorkspace({name:'First Firm'});const second=await atlas.createWorkspace({name:'Second Firm'});const adProviders=new ProviderRegistry('Advertising').register('meta',{availableFor(workspaceId){return workspaceId===first.id;},describe(){return{label:'Meta Ads',channels:['facebook'],workspaceId:first.id};},async createPausedCampaign(){return{externalId:'meta_1'};}});const marketing=new MarketingService(atlas,{adProviders,clock});assert.equal((await marketing.status(first.id)).adProviders.length,1);assert.equal((await marketing.status(second.id)).adProviders.length,0);const campaign=await marketing.createCampaign(second.id,{title:'Second campaign',practiceArea:'General law',channels:['facebook'],budgetMinor:10000,geography:'Delaware',radiusMiles:25,headline:'General legal information',body:'Learn about general legal topics.',landingPage:'https://second.example'},'usr_second');await assert.rejects(()=>marketing.prepareCampaign(second.id,campaign.id,{attorneyAdvertisingRulesReviewed:true,platformPoliciesReviewed:true,landingPageReviewed:true},'usr_second'),error=>error.code==='MARKETING_AD_PROVIDER_NOT_CONFIGURED');});
