import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { CmsExportMigrationService } from '../src/migration-import.js';

async function fixture(){const repository=new InMemoryRepository();const atlas=new AtlasService(repository,()=> '2026-07-13T15:00:00.000Z');const workspace=await atlas.createWorkspace({name:'Migration Firm'});return {repository,atlas,workspace,migration:new CmsExportMigrationService(atlas,()=> '2026-07-13T15:00:00.000Z')};}
const files=[{name:'matters.csv',content:'id,case_name,case_number,status\nm-1,Morgan v. Lakeside,CV-101,open\n'},{name:'contacts.csv',content:'id,name,email,phone,matter_id\nc-1,Taylor Morgan,taylor@example.test,555-0100,m-1\n'},{name:'tasks.json',content:JSON.stringify([{id:'t-1',title:'Prepare discovery responses',matter_id:'m-1',due_date:'2026-07-24'}])},{name:'calendar_events.csv',content:'id,title,matter_id,start,end\ne-1,Status conference,m-1,2026-08-01T14:00:00Z,2026-08-01T15:00:00Z\n'},{name:'invoices.csv',kind:'accounting',content:'id,title,matter_id,amount,status\na-1,Initial retainer,m-1,5000,issued\n'},{name:'emails.csv',content:'id,subject,matter_id,from,to,body\nmail-1,Discovery update,m-1,counsel@example.test,lawyer@example.test,Responses attached\n'},{name:'communications.csv',content:'id,title,matter_id,type,notes\ncom-1,Client call,m-1,phone,Requested status update\n'}];

test('migration preview classifies exported CSV and JSON without changing firm data',async()=>{const {atlas,workspace,migration}=await fixture();const before=(await atlas.listObjects(workspace.id,{})).length;const preview=migration.preview({provider:'clio',files});assert.equal(preview.canImport,true);assert.equal(preview.totalRecords,7);assert.deepEqual(preview.datasets.map(item=>item.kind),['matter','client','task','calendar','accounting','email','communication']);assert.equal((await atlas.listObjects(workspace.id,{})).length,before);});

test('export import creates canonical case-owned data with provenance and repeat-safe identity',async()=>{const {atlas,workspace,migration}=await fixture();const batch=await migration.import(workspace.id,{provider:'clio',files},'usr_owner');assert.equal(batch.state.status,'completed');assert.equal(batch.state.created,7);const objects=await atlas.listObjects(workspace.id,{});const matter=objects.find(item=>item.dimension==='matter');assert.equal(matter.title,'Morgan v. Lakeside');for(const type of ['client','task','calendar_event','accounting_entry','incoming_email','communication']){const object=objects.find(item=>item.type===type);assert.ok(object,`missing ${type}`);assert.equal(object.parentObjectId,matter.id);assert.equal(object.state.matterId,matter.id);assert.equal(object.state.externalSource.provider,'export:clio');}const repeated=await migration.import(workspace.id,{provider:'clio',files},'usr_owner');assert.equal(repeated.state.created,0);assert.equal(repeated.state.skipped,7);});

test('migration rejects unknown files before writing a batch',async()=>{const {atlas,workspace,migration}=await fixture();const preview=migration.preview({provider:'generic',files:[{name:'mystery.csv',content:'id,value\n1,x\n'}]});assert.equal(preview.canImport,false);await assert.rejects(()=>migration.import(workspace.id,{provider:'generic',files:[{name:'mystery.csv',content:'id,value\n1,x\n'}]},'usr_owner'),/Resolve preview errors/);assert.equal((await migration.list(workspace.id)).length,0);assert.equal((await atlas.listObjects(workspace.id,{})).length,0);});

test('CSV parser preserves quoted commas and JSON object exports with one collection',async()=>{const {workspace,migration,atlas}=await fixture();const input={provider:'mycase',files:[{name:'cases.csv',content:'id,name,status\n1,"Smith, Jordan",open\n'},{name:'tasks.json',content:JSON.stringify({tasks:[{id:'2',name:'Call client',case_id:'1'}]})}]};const result=await migration.import(workspace.id,input,'usr_owner');assert.equal(result.state.created,2);const objects=await atlas.listObjects(workspace.id,{});assert.equal(objects.find(item=>item.dimension==='matter').title,'Smith, Jordan');assert.ok(objects.find(item=>item.type==='task').parentObjectId);});
