import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { AtlasIntelligenceRuntime, IntelligenceProviderRegistry } from '../src/intelligence.js';
import { IntelligenceProjectionService } from '../src/intelligence-projection.js';
import { SituationalPlaybookEngine, SituationalSweepService } from '../src/situational-awareness.js';
import { AtlasIngestionService } from '../src/ingestion.js';

test('missed discovery deadlines autonomously prepare review work and While You Were Gone awareness',async()=>{
  const repository=new InMemoryRepository();const clock=()=> '2026-07-10T12:00:00.000Z';const service=new AtlasService(repository,clock);const workspace=await service.createWorkspace({name:'Aware Firm'});const matter=await service.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Reed v. Northline'});await service.createObject(workspace.id,{parentObjectId:matter.id,dimension:'operation',type:'deadline',title:'Discovery responses due',state:{date:'2026-07-01T00:00:00.000Z',deadlineType:'discovery',status:'open'}});
  for(const job of await repository.listIntelligenceJobs(workspace.id))await repository.completeIntelligenceJob(job.id,{},'setup',clock());
  const sweep=new SituationalSweepService(repository,clock);assert.equal((await sweep.run()).queued,1);assert.equal((await sweep.run()).queued,0);
  const provider={capabilities(){return {triggers:['deadline.missed']};},async analyze(){return {observations:[],actionProposals:[]};}};const registry=new IntelligenceProviderRegistry().register('awareness',provider);const runtime=new AtlasIntelligenceRuntime(repository,registry,{providerName:'awareness',projector:new IntelligenceProjectionService(clock),playbooks:new SituationalPlaybookEngine(),clock});await runtime.processNext();
  const home=await service.whileYouWereGone(workspace.id,'usr_attorney');const item=home[0];assert.equal(item.category,'missed_deadline');assert.equal(item.priority,'urgent');assert.deepEqual(item.actions.map((action)=>action.actionType).sort(),['create_document','create_task']);assert.match(item.actions.find((action)=>action.actionType==='create_document').input.content,/DRAFT FOR ATTORNEY REVIEW/);assert.equal(item.reviewStatus,'unseen');await service.updateAwarenessStatus(workspace.id,item.id,'usr_attorney','reviewed');assert.equal((await service.whileYouWereGone(workspace.id,'usr_attorney'))[0].reviewStatus,'reviewed');
});

test('approaching deadlines autonomously suggest matter preparation without a deadline menu',async()=>{
  const repository=new InMemoryRepository();const clock=()=> '2026-07-10T12:00:00.000Z';const service=new AtlasService(repository,clock);const workspace=await service.createWorkspace({name:'Forward Looking Firm'});const matter=await service.createObject(workspace.id,{dimension:'matter',type:'civil',title:'Reed v. Northline'});await service.createObject(workspace.id,{parentObjectId:matter.id,dimension:'operation',type:'deadline',title:'Summary judgment response due',state:{date:'2026-07-15T12:00:00.000Z',status:'open',assignedTo:'usr_attorney'}});await service.createObject(workspace.id,{parentObjectId:matter.id,dimension:'operation',type:'deadline',title:'Distant trial deadline',state:{date:'2026-08-15T12:00:00.000Z',status:'open'}});
  for(const job of await repository.listIntelligenceJobs(workspace.id))await repository.completeIntelligenceJob(job.id,{},'setup',clock());
  const sweep=new SituationalSweepService(repository,clock);assert.equal((await sweep.run()).queued,1);assert.equal((await sweep.run()).queued,0);
  const provider={capabilities(){return {triggers:['deadline.approaching']};},async analyze(){return {observations:[],actionProposals:[]};}};const runtime=new AtlasIntelligenceRuntime(repository,new IntelligenceProviderRegistry().register('deadline-awareness',provider),{providerName:'deadline-awareness',projector:new IntelligenceProjectionService(clock),playbooks:new SituationalPlaybookEngine(),clock});await runtime.processNext();
  const item=(await service.whileYouWereGone(workspace.id,'usr_attorney'))[0];assert.equal(item.category,'approaching_deadline');assert.equal(item.priority,'high');assert.equal(item.headline,'Approaching deadline requires preparation');assert.equal(item.actions.length,1);assert.equal(item.actions[0].actionType,'create_task');assert.equal(item.actions[0].input.matterId,matter.id);assert.equal(item.actions[0].input.dueDate,'2026-07-15T12:00:00.000Z');
});

test('phone calls and document/email events retain distinct situational categories',async()=>{const repository=new InMemoryRepository();const service=new AtlasService(repository);const workspace=await service.createWorkspace({name:'Events'});await service.createEvent(workspace.id,{type:'phone_call.received',actorId:'usr_1',source:'phone',data:{transcript:'Client requested a callback'}});const jobs=await repository.listIntelligenceJobs(workspace.id);assert.equal(jobs[0].triggerType,'phone_call.received');const engine=new SituationalPlaybookEngine();assert.equal(engine.apply(jobs[0],{observations:[],actionProposals:[]}).awareness.category,'phone_call');assert.equal(engine.apply({...jobs[0],triggerType:'attachment.received'},{observations:[],actionProposals:[]}).awareness.category,'document_upload');assert.equal(engine.apply({...jobs[0],triggerType:'email.received'},{observations:[],actionProposals:[]}).awareness.category,'incoming_email');});

test('situational playbooks deterministically prepare safe review work from extracted duties and deadlines',()=>{const engine=new SituationalPlaybookEngine();const email=engine.apply({triggerType:'email.received',payload:{email:{title:'Extension request',state:{from:'counsel@example.com'}}}},{observations:[{kind:'duty',data:{title:'Respond'},confidence:.9}],actionProposals:[]});assert.equal(email.actionProposals[0].actionType,'draft_email');assert.deepEqual(email.actionProposals[0].input.recipients,['counsel@example.com']);const call=engine.apply({triggerType:'phone_call.received',payload:{call:{}}},{observations:[{kind:'duty',data:{title:'Return call'},confidence:.9}],actionProposals:[]});assert.equal(call.actionProposals[0].actionType,'create_task');const document=engine.apply({triggerType:'attachment.received',payload:{document:{title:'subpoena.pdf'}}},{observations:[{kind:'deadline',data:{title:'Subpoena response',date:'2026-07-24'},confidence:.9}],actionProposals:[]});assert.equal(document.actionProposals[0].actionType,'create_task');assert.equal(document.actionProposals[0].input.dueDate,'2026-07-24');});

test('While You Were Gone suppresses background noise that needs no review',()=>{const output=new SituationalPlaybookEngine().apply({triggerType:'object.updated',payload:{}},{observations:[],actionProposals:[]});assert.equal(output.awareness,undefined);});

test('ingested phone activity autonomously becomes reviewable awareness without chat',async()=>{const repository=new InMemoryRepository();const clock=()=> '2026-07-10T12:00:00.000Z';const service=new AtlasService(repository,clock);const workspace=await service.createWorkspace({name:'Call Firm'});const ingestion=new AtlasIngestionService(repository,clock);await ingestion.ingestPhoneCall(workspace.id,{connector:'phone',externalId:'call-aware-1',direction:'incoming',transcript:'Client asks whether discovery was received.',durationSeconds:30},'usr_connector');const provider={capabilities(){return {triggers:['phone_call.received']};},async analyze(){return {observations:[{kind:'duty',data:{title:'Return client call'},confidence:.96,sourceLocation:null}],actionProposals:[{actionType:'create_task',input:{title:'Return client call'}}]};}};const runtime=new AtlasIntelligenceRuntime(repository,new IntelligenceProviderRegistry().register('call-ai',provider),{providerName:'call-ai',projector:new IntelligenceProjectionService(clock),playbooks:new SituationalPlaybookEngine(),clock});await runtime.processNext();const feed=await service.whileYouWereGone(workspace.id,'usr_attorney');assert.equal(feed[0].category,'phone_call');assert.equal(feed[0].priority,'high');assert.equal(feed[0].observations[0].kind,'duty');assert.equal(feed[0].actions[0].actionType,'create_task');});
