import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { Readable } from 'node:stream';
import { createAtlasHandler } from '../src/http.js';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { SmsAssistantService } from '../src/sms-assistant.js';
import { TwilioVoiceAdapter } from '../src/telephony-provider-adapters.js';

const base='https://atlas.example';const token='sms-http-token';
function signature(path,params){const payload=`${base}${path}`+Object.keys(params).sort().map(key=>`${key}${params[key]}`).join('');return createHmac('sha1',token).update(payload).digest('base64');}
async function form(handler,path,params){const request=Readable.from([Buffer.from(new URLSearchParams(params).toString())]);request.method='POST';request.url=path;request.headers={'content-type':'application/x-www-form-urlencoded','x-twilio-signature':signature(path,params)};return new Promise((resolve,reject)=>{const response={writeHead(status,headers){this.status=status;this.headers=headers;},end(body){resolve({status:this.status,headers:this.headers,body:String(body)});}};Promise.resolve(handler(request,response)).catch(reject);});}

test('signed inbound SMS webhook returns safe TwiML and creates canonical review work',async()=>{const repository=new InMemoryRepository();const atlas=new AtlasService(repository);const workspace=await atlas.createWorkspace({name:'SMS HTTP Firm'});const telephony=new TwilioVoiceAdapter({authToken:token,publicBaseUrl:base});const sms=new SmsAssistantService(atlas,{messagingProvider:telephony});await sms.configure(workspace.id,{acknowledgement:'Atlas received your text for firm review.'},'usr_owner');const handler=createAtlasHandler(atlas,{config:{maxBodyBytes:100_000,corsOrigins:[]},telephony,sms});const path=`/v1/messaging/twilio/${workspace.id}/incoming`;const result=await form(handler,path,{MessageSid:'SM-HTTP-1',From:'+15550001111',To:'+15559990000',Body:'Please call me about my case',NumMedia:'0'});assert.equal(result.status,200);assert.match(result.headers['content-type'],/application\/xml/);assert.match(result.body,/Atlas received your text/);const status=await sms.status(workspace.id);assert.equal(status.messages.length,1);assert.equal(status.drafts.length,1);assert.equal((await atlas.listObjects(workspace.id,{type:'task'})).length,1);});

test('forged inbound SMS signatures fail closed before data creation',async()=>{const repository=new InMemoryRepository();const atlas=new AtlasService(repository);const workspace=await atlas.createWorkspace({name:'SMS Forgery Firm'});const telephony=new TwilioVoiceAdapter({authToken:token,publicBaseUrl:base});const sms=new SmsAssistantService(atlas,{messagingProvider:telephony});await sms.configure(workspace.id,{},'usr_owner');const handler=createAtlasHandler(atlas,{config:{maxBodyBytes:100_000,corsOrigins:[]},telephony,sms});const path=`/v1/messaging/twilio/${workspace.id}/incoming`;const request=Readable.from([Buffer.from('MessageSid=SM-BAD&Body=Forged')]);request.method='POST';request.url=path;request.headers={'x-twilio-signature':'forged'};const result=await new Promise((resolve,reject)=>{const response={writeHead(status){this.status=status;},end(body){resolve({status:this.status,body:JSON.parse(String(body))});}};Promise.resolve(handler(request,response)).catch(reject);});assert.equal(result.status,401);assert.equal(result.body.error.code,'TELEPHONY_SIGNATURE_INVALID');assert.equal((await sms.status(workspace.id)).messages.length,0);});
