import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { SmsAssistantService } from '../src/sms-assistant.js';

async function fixture(options={}){const repository=new InMemoryRepository();const atlas=new AtlasService(repository,()=> '2026-07-13T16:00:00.000Z');const workspace=await atlas.createWorkspace({name:'Text Firm'});const sms=new SmsAssistantService(atlas,{clock:()=> '2026-07-13T16:00:00.000Z',...options});await sms.configure(workspace.id,{provider:'twilio',autoAcknowledgement:true},'usr_owner');return {repository,atlas,workspace,sms};}

test('incoming texts become canonical messages, review work, and unsent drafts',async()=>{const {atlas,workspace,sms}=await fixture();await atlas.createObject(workspace.id,{dimension:'client',type:'client',title:'Known Client',state:{phone:'+15550001111'}});const result=await sms.receive(workspace.id,{externalMessageId:'SM-1',from:'+15550001111',to:'+15559990000',body:'Can I get an update on my case?',provider:'twilio'});assert.equal(result.message.type,'sms_message');assert.equal(result.message.state.knownCallerTitle,'Known Client');assert.equal(result.work.type,'task');assert.equal(result.draft.type,'sms_draft');assert.equal(result.draft.state.sent,false);assert.equal(result.draft.state.requiresHumanApproval,true);assert.match(result.reply,/automated assistant/i);const events=await atlas.listEvents(workspace.id,result.message.id);assert.ok(events.some(event=>event.type==='sms.received'));const duplicate=await sms.receive(workspace.id,{externalMessageId:'SM-1',from:'+15550001111',to:'+15559990000',body:'duplicate'});assert.equal(duplicate.duplicate,true);});

test('opt-out keywords are retained without acknowledgement, draft, or follow-up work',async()=>{const {workspace,sms}=await fixture();const result=await sms.receive(workspace.id,{externalMessageId:'SM-STOP',from:'+15550002222',to:'+15559990000',body:'STOP'});assert.equal(result.reply,null);assert.equal(result.draft,null);assert.equal(result.work,null);const status=await sms.status(workspace.id);assert.equal(status.messages[0].state.status,'opted_out');assert.equal(status.messages[0].state.optOut,true);});

test('substantive outbound text requires a pending draft, explicit human confirmation, and provider send',async()=>{const sent=[];const provider={describe(){return {provider:'fake-sms'};},async sendMessage(input){sent.push(input);return {id:'SM-OUT',status:'queued',from:'+15559990000'};}};const {workspace,sms}=await fixture({messagingProvider:provider});const draft=await sms.createDraft(workspace.id,{to:'+15550003333',body:'Your appointment request was approved.'},'usr_attorney');await assert.rejects(()=>sms.sendDraft(workspace.id,draft.id,{version:draft.version},'usr_attorney'),/Explicit send confirmation/);const result=await sms.sendDraft(workspace.id,draft.id,{version:draft.version,confirm:true},'usr_attorney');assert.equal(sent.length,1);assert.equal(result.draft.state.status,'sent');assert.equal(result.message.state.approvedBy,'usr_attorney');await assert.rejects(()=>sms.sendDraft(workspace.id,draft.id,{version:result.draft.version,confirm:true},'usr_attorney'),/pending unsent/);});

test('an opted-out recipient cannot be sent a later approved draft',async()=>{const sent=[];const provider={describe(){return {provider:'fake-sms'};},async sendMessage(input){sent.push(input);return {id:'never',status:'queued'};}};const {workspace,sms}=await fixture({messagingProvider:provider});await sms.receive(workspace.id,{externalMessageId:'SM-STOP-LATER',from:'+15550004444',to:'+15559990000',body:'STOP'});const draft=await sms.createDraft(workspace.id,{to:'+1 (555) 000-4444',body:'This must not be sent.'},'usr_attorney');await assert.rejects(()=>sms.sendDraft(workspace.id,draft.id,{version:draft.version,confirm:true},'usr_attorney'),/opted out/);assert.equal(sent.length,0);});

test('AI classification is interchangeable but cannot directly send a text',async()=>{const intentProvider={async classify(){return 'schedule';}};const {workspace,sms}=await fixture({intentProvider});const result=await sms.receive(workspace.id,{externalMessageId:'SM-AI',from:'+15550004444',to:'+15559990000',body:'Can we find a time next week?'});assert.equal(result.message.state.intent,'schedule');assert.equal(result.draft.state.status,'pending_review');assert.equal(result.draft.state.sent,false);});
