import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { SmsAssistantService } from '../src/sms-assistant.js';

async function fixture(options={}){const repository=new InMemoryRepository();const atlas=new AtlasService(repository,()=> '2026-07-13T16:00:00.000Z');const workspace=await atlas.createWorkspace({name:'Text Firm'});const sms=new SmsAssistantService(atlas,{clock:()=> '2026-07-13T16:00:00.000Z',...options});await sms.configure(workspace.id,{provider:'twilio',autoAcknowledgement:true},'usr_owner');return {repository,atlas,workspace,sms};}

test('incoming texts become canonical messages, review work, and unsent drafts',async()=>{const {atlas,workspace,sms}=await fixture();await atlas.createObject(workspace.id,{dimension:'client',type:'client',title:'Known Client',state:{phone:'+15550001111'}});const result=await sms.receive(workspace.id,{externalMessageId:'SM-1',from:'+15550001111',to:'+15559990000',body:'Can I get an update on my case?',provider:'twilio'});assert.equal(result.message.type,'sms_message');assert.equal(result.message.state.knownCallerTitle,'Known Client');assert.equal(result.work.type,'task');assert.equal(result.draft.type,'sms_draft');assert.equal(result.draft.state.sent,false);assert.equal(result.draft.state.requiresHumanApproval,true);assert.match(result.reply,/automated assistant/i);const events=await atlas.listEvents(workspace.id,result.message.id);assert.ok(events.some(event=>event.type==='sms.received'));const duplicate=await sms.receive(workspace.id,{externalMessageId:'SM-1',from:'+15550001111',to:'+15559990000',body:'duplicate'});assert.equal(duplicate.duplicate,true);});

test('opt-out keywords are retained without acknowledgement, draft, or follow-up work',async()=>{const {workspace,sms}=await fixture();const result=await sms.receive(workspace.id,{externalMessageId:'SM-STOP',from:'+15550002222',to:'+15559990000',body:'STOP'});assert.equal(result.reply,null);assert.equal(result.draft,null);assert.equal(result.work,null);const status=await sms.status(workspace.id);assert.equal(status.messages[0].state.status,'opted_out');assert.equal(status.messages[0].state.optOut,true);});

test('substantive outbound text requires a pending draft, explicit human confirmation, and provider send',async()=>{const sent=[];const provider={describe(){return {provider:'fake-sms'};},async sendMessage(input){sent.push(input);return {id:'SM-OUT',status:'queued',from:'+15559990000'};}};const {workspace,sms}=await fixture({messagingProvider:provider});const draft=await sms.createDraft(workspace.id,{to:'+15550003333',body:'Your appointment request was approved.'},'usr_attorney');await assert.rejects(()=>sms.sendDraft(workspace.id,draft.id,{version:draft.version},'usr_attorney'),/Explicit send confirmation/);const result=await sms.sendDraft(workspace.id,draft.id,{version:draft.version,confirm:true},'usr_attorney');assert.equal(sent.length,1);assert.equal(result.draft.state.status,'sent');assert.equal(result.message.state.approvedBy,'usr_attorney');await assert.rejects(()=>sms.sendDraft(workspace.id,draft.id,{version:result.draft.version,confirm:true},'usr_attorney'),/pending unsent/);});

test('an opted-out recipient cannot be sent a later approved draft',async()=>{const sent=[];const provider={describe(){return {provider:'fake-sms'};},async sendMessage(input){sent.push(input);return {id:'never',status:'queued'};}};const {workspace,sms}=await fixture({messagingProvider:provider});await sms.receive(workspace.id,{externalMessageId:'SM-STOP-LATER',from:'+15550004444',to:'+15559990000',body:'STOP'});const draft=await sms.createDraft(workspace.id,{to:'+1 (555) 000-4444',body:'This must not be sent.'},'usr_attorney');await assert.rejects(()=>sms.sendDraft(workspace.id,draft.id,{version:draft.version,confirm:true},'usr_attorney'),/opted out/);assert.equal(sent.length,0);});

test('AI classification is interchangeable but cannot directly send a text',async()=>{const intentProvider={async classify(){return 'schedule';}};const {workspace,sms}=await fixture({intentProvider});const result=await sms.receive(workspace.id,{externalMessageId:'SM-AI',from:'+15550004444',to:'+15559990000',body:'Can we find a time next week?'});assert.equal(result.message.state.intent,'schedule');assert.equal(result.draft.state.status,'pending_review');assert.equal(result.draft.state.sent,false);});

test('configured consultation alerts text the attorney and record the operational authorization',async()=>{const sent=[];const provider={describe(){return{provider:'fake-sms'};},async sendMessage(input){sent.push(input);return{id:'SM-ATTORNEY',status:'sent',from:'+15559990000'};}};const {workspace,sms}=await fixture({messagingProvider:provider});await sms.configure(workspace.id,{provider:'twilio',consultationNotifications:true,consultationNotificationNumber:'+1 (813) 555-0100'},'usr_owner');const result=await sms.sendConsultationNotification(workspace.id,{consultationRequestId:'obj_request',body:'Atlas: reply 1, 2, or 3 to select a proposed consultation time.'});assert.equal(sent.length,1);assert.equal(sent[0].to,'+18135550100');assert.equal(result.draft.state.authorizationType,'attorney_consultation_notification');assert.equal(result.message.state.status,'sent');});

test('client consultation confirmation requires recorded text consent',async()=>{const sent=[];const provider={describe(){return{provider:'fake-sms'};},async sendMessage(input){sent.push(input);return{id:'SM-CLIENT',status:'sent',from:'+15559990000'};}};const {workspace,sms}=await fixture({messagingProvider:provider});await assert.rejects(()=>sms.sendConsultationConfirmation(workspace.id,{consultationRequestId:'obj_request',to:'+17275550100',body:'Confirmed',textConsent:false},'usr_attorney'),error=>error.code==='SMS_CONSULTATION_CONSENT_REQUIRED');const result=await sms.sendConsultationConfirmation(workspace.id,{consultationRequestId:'obj_request',to:'+17275550100',body:'Confirmed. Reply STOP to opt out.',textConsent:true,authorizationType:'client_consultation_confirmation'},'usr_attorney');assert.equal(sent.length,1);assert.equal(result.draft.state.authorizationType,'client_consultation_confirmation');assert.equal(result.draft.state.approvedBy,'usr_attorney');});

test('a consultation scheduling reply is canonically recorded without creating a generic draft',async()=>{let consultationId;const {workspace,sms,atlas}=await fixture({consultationReplyHandler:async(_workspace,input)=>({handled:true,reply:'Confirmed.',result:{request:{id:consultationId},body:input.body}})});const consultation=await atlas.createObject(workspace.id,{dimension:'operation',type:'website_consultation_request',title:'Consultation request',state:{status:'awaiting_client_confirmation'},actorId:'usr_owner'});consultationId=consultation.id;const result=await sms.receive(workspace.id,{externalMessageId:'SM-CONSULT',from:'+18135550199',to:'+18135550000',body:'YES',provider:'twilio'});assert.equal(result.reply,'Confirmed.');assert.equal(result.message.state.intent,'consultation_scheduling');assert.equal(result.message.state.consultationRequestId,consultation.id);assert.equal(result.draft,null);assert.equal(result.work,null);});

test('a reply from the configured attorney number is routed as an attorney scheduling decision',async()=>{let receivedRole=null;let requestId=null;const {workspace,sms,atlas}=await fixture({consultationReplyHandler:async(_workspace,input)=>{receivedRole=input.role;return{handled:true,reply:'Option selected.',request:{id:requestId}};}});const request=await atlas.createObject(workspace.id,{dimension:'operation',type:'website_consultation_request',title:'Consultation request',state:{status:'pending_attorney_confirmation'},actorId:'usr_owner'});requestId=request.id;await sms.configure(workspace.id,{provider:'twilio',consultationNotifications:true,consultationNotificationNumber:'+1 (813) 555-0100'},'usr_owner');const result=await sms.receive(workspace.id,{externalMessageId:'SM-ATTORNEY-REPLY',from:'+18135550100',to:'+18135550000',body:'2',provider:'twilio'});assert.equal(receivedRole,'attorney');assert.equal(result.message.state.senderRole,'attorney');assert.equal(result.reply,'Option selected.');assert.equal(result.draft,null);assert.equal(result.work,null);});
