import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { SocialMediaService } from '../src/social-media.js';

const model={async complete(){return {text:JSON.stringify({title:'Know your discovery obligations',content:'Discovery deadlines deserve early attention. This post provides general information and is not legal advice.',hashtags:['LegalEducation','CivilLitigation']})};}};

test('attorney-selected topics produce provider-neutral review suggestions in While You Were Gone',async()=>{const repository=new InMemoryRepository();const atlas=new AtlasService(repository,()=> '2026-07-14T16:00:00.000Z');const workspace=await atlas.createWorkspace({name:'Social Firm'});const social=new SocialMediaService(atlas,model,()=> '2026-07-14T16:00:00.000Z');const configuration=await social.configure(workspace.id,{enabled:true,networks:['linkedin','facebook'],topics:['Discovery education'],cadence:'manual',tone:'professional'},'usr_attorney');assert.equal(configuration.type,'social_media_configuration');const suggestion=await social.suggest(workspace.id,{topic:'Discovery education'},'usr_attorney');assert.equal(suggestion.proposal.actionType,'create_social_post');assert.equal(suggestion.proposal.status,'pending');assert.equal(suggestion.awareness.category,'social_media_suggestion');const feed=await atlas.whileYouWereGone(workspace.id,'usr_attorney');assert.equal(feed[0].actions[0].id,suggestion.proposal.id);assert.match(feed[0].summary,/Nothing has been published/);const approved=await atlas.decideAiActionProposal(workspace.id,suggestion.proposal.id,{version:1,decision:'approve'},'usr_attorney');assert.equal(approved.result.type,'social_post_draft');assert.equal(approved.result.state.published,false);assert.equal(approved.result.state.publishingEnabled,false);assert.equal(approved.result.state.content.includes('not legal advice'),true);});

test('social suggestions remain opt-in and fail honestly without an AI provider',async()=>{const repository=new InMemoryRepository();const atlas=new AtlasService(repository);const workspace=await atlas.createWorkspace({name:'Opt In Firm'});const social=new SocialMediaService(atlas,null);await social.configure(workspace.id,{enabled:false,networks:['linkedin'],topics:[],cadence:'manual'},'usr_attorney');await assert.rejects(()=>social.suggest(workspace.id,{topic:'Estate planning'},'usr_attorney'),error=>error.code==='SOCIAL_SUGGESTIONS_DISABLED');await social.configure(workspace.id,{enabled:true,networks:['linkedin'],topics:['Estate planning'],cadence:'manual'},'usr_attorney');await assert.rejects(()=>social.suggest(workspace.id,{topic:'Estate planning'},'usr_attorney'),error=>error.code==='SOCIAL_AI_UNAVAILABLE');});

test('social configuration accepts supported channels but never enables publishing',async()=>{const repository=new InMemoryRepository();const atlas=new AtlasService(repository);const workspace=await atlas.createWorkspace({name:'Safe Social Firm'});const social=new SocialMediaService(atlas,model);await assert.rejects(()=>social.configure(workspace.id,{enabled:true,networks:['unknown'],topics:['Legal updates']},'usr_attorney'),error=>error.code==='SOCIAL_NETWORK_INVALID');const configured=await social.configure(workspace.id,{enabled:true,networks:['instagram','x'],topics:['Legal updates'],cadence:'manual'},'usr_attorney');assert.equal(configured.state.publishingEnabled,false);const status=await social.status(workspace.id);assert.equal(status.providers.every(provider=>provider.publishing===false),true);assert.equal(status.providers.every(provider=>provider.connection==='oauth_required'),true);});
