import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { StructuredModelVoiceIntentProvider, VoiceAssistantService } from '../src/voice-assistant.js';

async function fixture(){const repository=new InMemoryRepository();const atlas=new AtlasService(repository,()=> '2026-07-13T14:00:00.000Z');const workspace=await atlas.createWorkspace({name:'Voice Firm'});const voice=new VoiceAssistantService(atlas,{clock:()=> '2026-07-13T14:00:00.000Z'});await voice.configure(workspace.id,{provider:'twilio',greeting:'Thank you for calling Voice Firm. How may I help?',transferNumber:'+15551230000',faqs:[{question:'Hours',answer:'The firm is open Monday through Friday from nine to five.',keywords:['hours','open']}]},'usr_owner');return {repository,atlas,workspace,voice};}

test('inbound calls become canonical firm sessions with automated-assistant disclosure',async()=>{const {voice,workspace}=await fixture();const result=await voice.startCall(workspace.id,{externalCallId:'CA-1',from:'+15550001111',to:'+15559990000'});assert.equal(result.action,'gather');assert.match(result.prompt,/automated virtual assistant/i);assert.equal(result.call.type,'voice_call_session');assert.equal(result.call.state.legalAdviceProvided,false);const duplicate=await voice.startCall(workspace.id,{externalCallId:'CA-1',from:'+15550001111'});assert.equal(duplicate.duplicate,true);});

test('new-client intake is staged and creates review work without forming representation',async()=>{const {voice,workspace,atlas}=await fixture();await voice.startCall(workspace.id,{externalCallId:'CA-2',from:'+15550002222'});const first=await voice.handleTurn(workspace.id,{externalCallId:'CA-2',text:'I am a potential new client'});assert.equal(first.call.state.stage,'intake_name');assert.match(first.prompt,/does not create an attorney-client relationship/i);const second=await voice.handleTurn(workspace.id,{externalCallId:'CA-2',text:'Jordan Lee'});assert.equal(second.call.state.stage,'intake_issue');const third=await voice.handleTurn(workspace.id,{externalCallId:'CA-2',text:'I need help responding to a contract lawsuit'});assert.equal(third.work.type,'prospective_client_intake');assert.equal(third.work.state.requiresAttorneyReview,true);assert.equal((await atlas.getObject(workspace.id,third.work.id)).state.sourceCallId,third.call.id);});

test('legal questions and existing-client calls create guarded attorney work without disclosing case facts',async()=>{const {voice,workspace,atlas}=await fixture();await atlas.createObject(workspace.id,{dimension:'client',type:'client',title:'Known Client',state:{phone:'+15550003333'}});await voice.startCall(workspace.id,{externalCallId:'CA-3',from:'+15550003333'});const status=await voice.handleTurn(workspace.id,{externalCallId:'CA-3',text:'I am an existing client. What is happening in my case?'});assert.match(status.prompt,/cannot disclose case information/i);assert.equal(status.work.type,'task');const advice=await voice.handleTurn(workspace.id,{externalCallId:'CA-3',text:'Will I win and what should I do?'});assert.match(advice.prompt,/cannot provide legal advice/i);assert.equal(advice.call.state.legalAdviceProvided,false);});

test('urgent calls transfer only to the firm-configured destination and routine FAQs do not create work',async()=>{const {voice,workspace}=await fixture();await voice.startCall(workspace.id,{externalCallId:'CA-4',from:'+15550004444'});const faq=await voice.handleTurn(workspace.id,{externalCallId:'CA-4',text:'What are your office hours?'});assert.equal(faq.work,null);assert.match(faq.prompt,/Monday through Friday/i);const urgent=await voice.handleTurn(workspace.id,{externalCallId:'CA-4',text:'This is urgent, my hearing is today'});assert.equal(urgent.action,'transfer');assert.equal(urgent.transferNumber,'+15551230000');});

test('completed calls retain the transcript and enter native phone-call awareness',async()=>{const {voice,workspace,atlas}=await fixture();await voice.startCall(workspace.id,{externalCallId:'CA-5',from:'+15550005555'});await voice.handleTurn(workspace.id,{externalCallId:'CA-5',text:'Please ask an attorney to call me back'});const completed=await voice.completeCall(workspace.id,{externalCallId:'CA-5',status:'completed',durationSeconds:42});assert.equal(completed.state.status,'completed');assert.equal(completed.state.durationSeconds,42);assert.ok(completed.state.createdWorkIds.length);const events=await atlas.listEvents(workspace.id,completed.id);assert.ok(events.some(event=>event.type==='phone_call.received'&&event.data.transcript.length));});

test('interchangeable AI models can classify voice turns without owning call safety or persistence',async()=>{const model={async complete(request){assert.equal(request.context.channel,'voice');return {text:JSON.stringify({intent:'schedule'})};}};const provider=new StructuredModelVoiceIntentProvider(model);assert.equal(await provider.classify({text:'Could I come in next week?',context:{knownCaller:false}}),'schedule');const fallback=new StructuredModelVoiceIntentProvider({async complete(){throw new Error('provider unavailable');}});const {voice,workspace}=await fixture();voice.intentProvider=fallback;await voice.startCall(workspace.id,{externalCallId:'CA-6',from:'+15550006666'});const result=await voice.handleTurn(workspace.id,{externalCallId:'CA-6',text:'Please call me back'});assert.equal(result.work.type,'task');});
