import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { Readable } from 'node:stream';
import { createAtlasHandler } from '../src/http.js';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { VoiceAssistantService } from '../src/voice-assistant.js';
import { TwilioVoiceAdapter } from '../src/telephony-provider-adapters.js';

const base='https://atlas.example';const token='voice-http-token';
function signature(path,params){const payload=`${base}${path}`+Object.keys(params).sort().map(key=>`${key}${params[key]}`).join('');return createHmac('sha1',token).update(payload).digest('base64');}
async function form(handler,path,params){const body=new URLSearchParams(params).toString();const request=Readable.from([Buffer.from(body)]);request.method='POST';request.url=path;request.headers={'content-type':'application/x-www-form-urlencoded','x-twilio-signature':signature(path,params)};return new Promise((resolve,reject)=>{const response={writeHead(status,headers){this.status=status;this.headers=headers;},end(content){resolve({status:this.status,headers:this.headers,body:String(content)});}};Promise.resolve(handler(request,response)).catch(reject);});}

test('signed live voice webhooks answer, process speech, and close a canonical call',async()=>{const repository=new InMemoryRepository();const atlas=new AtlasService(repository);const workspace=await atlas.createWorkspace({name:'HTTP Voice Firm'});const voice=new VoiceAssistantService(atlas);await voice.configure(workspace.id,{greeting:'Thank you for calling HTTP Voice Firm.'},'usr_owner');const telephony=new TwilioVoiceAdapter({authToken:token,publicBaseUrl:base});const handler=createAtlasHandler(atlas,{config:{maxBodyBytes:1_048_576,corsOrigins:[]},voice,telephony});const incomingPath=`/v1/voice/twilio/${workspace.id}/incoming`;const incoming=await form(handler,incomingPath,{CallSid:'CA-HTTP-1',From:'+15550001111',To:'+15559990000'});assert.equal(incoming.status,200);assert.match(incoming.headers['content-type'],/application\/xml/);assert.match(incoming.body,/<Gather/);const turnPath=`/v1/voice/twilio/${workspace.id}/turn`;const turn=await form(handler,turnPath,{CallSid:'CA-HTTP-1',SpeechResult:'Please have an attorney call me back'});assert.match(turn.body,/callback request/i);const statusPath=`/v1/voice/twilio/${workspace.id}/status`;const status=await form(handler,statusPath,{CallSid:'CA-HTTP-1',CallStatus:'completed',CallDuration:'32'});assert.equal(status.status,200);const call=(await voice.status(workspace.id)).calls[0];assert.equal(call.state.status,'completed');assert.ok(call.state.createdWorkIds.length);});

test('live voice webhooks reject forged carrier signatures',async()=>{const repository=new InMemoryRepository();const atlas=new AtlasService(repository);const workspace=await atlas.createWorkspace({name:'Signature Firm'});const voice=new VoiceAssistantService(atlas);await voice.configure(workspace.id,{},'usr_owner');const telephony=new TwilioVoiceAdapter({authToken:token,publicBaseUrl:base});const handler=createAtlasHandler(atlas,{config:{maxBodyBytes:1_048_576,corsOrigins:[]},voice,telephony});const path=`/v1/voice/twilio/${workspace.id}/incoming`;const request=Readable.from([Buffer.from('CallSid=CA-FORGED')]);request.method='POST';request.url=path;request.headers={'x-twilio-signature':'forged'};const result=await new Promise((resolve,reject)=>{const response={writeHead(status){this.status=status;},end(content){resolve({status:this.status,body:JSON.parse(String(content))});}};Promise.resolve(handler(request,response)).catch(reject);});assert.equal(result.status,401);assert.equal(result.body.error.code,'TELEPHONY_SIGNATURE_INVALID');});
