import test from 'node:test';
import assert from 'node:assert/strict';
import { OpenAiWebResearchProvider, createWebResearchProvider } from '../src/ai-providers.js';

function response(body,status=200,requestId=null){return {ok:status>=200&&status<300,status,headers:{get:name=>name==='x-request-id'?requestId:null},async json(){return body;}};}

test('OpenAI web research sends only a public query and returns normalized clickable citations',async()=>{const requests=[];const provider=new OpenAiWebResearchProvider({apiKey:'test-key',model:'model-a',searchContextSize:'high',transport:async(url,options)=>{requests.push({url,body:JSON.parse(options.body),headers:options.headers});return response({model:'model-a',output:[{type:'web_search_call',action:{type:'search',sources:[{url:'https://court.example/opinion',title:'Court opinion'}]}},{type:'message',content:[{type:'output_text',text:'The public standard requires proportionality.',annotations:[{type:'url_citation',url:'https://court.example/opinion',title:'Court opinion'},{type:'url_citation',url:'https://rules.example/rule-26',title:'Rule 26'}]}]}],usage:{input_tokens:12,output_tokens:8,total_tokens:20}});}});const result=await provider.search({query:'current federal discovery proportionality standard'});assert.equal(requests[0].body.tools[0].type,'web_search');assert.equal(requests[0].body.tools[0].external_web_access,true);assert.equal(requests[0].body.tools[0].search_context_size,'high');assert.equal(requests[0].body.tool_choice,'required');assert.deepEqual(requests[0].body.include,['web_search_call.action.sources']);assert.equal(requests[0].body.store,false);assert.equal(requests[0].body.input.at(-1).content,'current federal discovery proportionality standard');assert.equal(JSON.stringify(requests[0].body).includes('firm-secret'),false);assert.equal(result.answer,'The public standard requires proportionality.');assert.deepEqual(result.sources,[{url:'https://court.example/opinion',title:'Court opinion'},{url:'https://rules.example/rule-26',title:'Rule 26'}]);assert.deepEqual(result.usage,{inputTokens:12,outputTokens:8,totalTokens:20});});

test('web research fails closed on provider errors or uncited output',async()=>{const base={apiKey:'test-key',model:'model-a'};await assert.rejects(()=>new OpenAiWebResearchProvider({...base,transport:async()=>{throw new Error('network');}}).search({query:'public law'}),error=>error.code==='WEB_RESEARCH_UNAVAILABLE');await assert.rejects(()=>new OpenAiWebResearchProvider({...base,transport:async()=>response({},401,'req_web')}).search({query:'public law'}),error=>error.code==='WEB_RESEARCH_AUTHENTICATION_FAILED'&&error.details.requestId==='req_web');await assert.rejects(()=>new OpenAiWebResearchProvider({...base,transport:async()=>response({output:[{type:'message',content:[{type:'output_text',text:'No citation'}]}]})}).search({query:'public law'}),error=>error.code==='WEB_RESEARCH_INVALID_RESPONSE');});

test('web research provider remains replaceable and disabled by default',()=>{const injected={capabilities:()=>({liveWeb:true}),search:async()=>({answer:'ok',sources:[]})};assert.equal(createWebResearchProvider({aiWebSearchEnabled:false},{}),null);assert.equal(createWebResearchProvider({aiWebSearchEnabled:true},{webResearchProvider:injected}),injected);});
