import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { createAtlasHandler } from '../src/http.js';
import { CRIMINAL_DEFENSE_TEMPLATE, WebsiteBuilderService, normalizeWebsiteDraft, renderWebsitePage, renderWebsiteRobots, renderWebsiteSitemap, websiteSeoReadiness } from '../src/website-builder.js';

const clock=()=> '2026-07-14T20:30:00.000Z';
const copy=value=>JSON.parse(JSON.stringify(value));
async function get(handler,url){let status=0,headers={},body=Buffer.alloc(0);await handler({method:'GET',url,headers:{},socket:{remoteAddress:'127.0.0.1'}},{writeHead(value,nextHeaders){status=value;headers=nextHeaders;},end(value){body=Buffer.isBuffer(value)?value:Buffer.from(value??'');}});return{status,headers,text:body.toString()};}

function releaseReadySite(){const site=copy(CRIMINAL_DEFENSE_TEMPLATE);site.firm={...site.firm,name:'Meridian Criminal Defense',shortName:'Meridian Defense',phone:'(813) 410-2020',email:'intake@meridiandefense.com',domain:'https://www.meridiandefense.com',attorneyName:'Alex Morgan',attorneyVerified:true,officeVerified:true};site.pages=site.pages.map(page=>({...page,author:'Alex Morgan',localEvidenceVerified:page.type==='location'?true:page.localEvidenceVerified}));return site;}

test('criminal-defense template is original, server rendered, connected, and safely noindex',()=>{const rendered=renderWebsitePage(CRIMINAL_DEFENSE_TEMPLATE,'/',{routePrefix:'/website-preview',nonce:'test-nonce'});assert.equal(rendered.status,200);assert.match(rendered.html,/Florida Criminal Defense Lawyers/);assert.match(rendered.html,/name="robots" content="noindex,nofollow,noarchive"/);assert.match(rendered.html,/application\/ld\+json/);assert.match(rendered.html,/BreadcrumbList/);assert.match(rendered.html,/\/website-preview\/practice-areas\/dui-defense\//);assert.match(rendered.html,/Atlas website-builder preview/);assert.doesNotMatch(rendered.html,/Musca Law/i);assert.doesNotMatch(rendered.html,/guaranteed result/i);});

test('renderer escapes firm content in visible markup and structured data',()=>{const site=copy(CRIMINAL_DEFENSE_TEMPLATE);site.firm.name='<img src=x onerror=alert(1)>';site.firm.shortName='<script>alert(1)</script>';const rendered=renderWebsitePage(site,'/',{nonce:'safe'});assert.doesNotMatch(rendered.html,/<img src=x/);assert.doesNotMatch(rendered.html,/<script>alert/);assert.match(rendered.html,/&lt;img src=x onerror=alert\(1\)&gt;/);assert.match(rendered.html,/\\u003cimg src=x/);});

test('SEO release gate blocks fictional identity and unverified local pages',()=>{const readiness=websiteSeoReadiness(CRIMINAL_DEFENSE_TEMPLATE);assert.equal(readiness.ready,false);assert.ok(readiness.issues.some(item=>item.code==='IDENTITY_PLACEHOLDER'));assert.ok(readiness.issues.some(item=>item.code==='ATTORNEY_UNVERIFIED'));assert.equal(readiness.issues.filter(item=>item.code==='LOCAL_EVIDENCE_UNVERIFIED').length,2);assert.equal(renderWebsiteRobots(CRIMINAL_DEFENSE_TEMPLATE,{preview:true}),'User-agent: *\nDisallow: /\n');});

test('complete verified site passes the coded SEO readiness contract but remains noindex before publishing',()=>{const site=releaseReadySite();const readiness=websiteSeoReadiness(site);assert.deepEqual(readiness.issues,[]);assert.equal(readiness.ready,true);const normalized=normalizeWebsiteDraft({...site,status:'release_candidate',indexable:true});assert.equal(normalized.indexable,false);const rendered=renderWebsitePage(normalized,'/locations/tampa/',{nonce:'release'});assert.match(rendered.html,/noindex,nofollow,noarchive/);assert.match(rendered.html,/Tampa Criminal Defense Lawyer/);assert.match(renderWebsiteSitemap(site),/<loc>https:\/\/www\.meridiandefense\.com\/locations\/tampa\/<\/loc>/);});

test('saving and preparing a website uses canonical objects, events, and intelligence jobs',async()=>{const repository=new InMemoryRepository();const atlas=new AtlasService(repository,clock);const workspace=await atlas.createWorkspace({name:'Website Firm'});const builder=new WebsiteBuilderService(atlas,clock);const saved=await builder.save(workspace.id,{site:releaseReadySite()},'usr_owner');assert.equal(saved.type,'website_site');assert.equal(saved.dimension,'operation');assert.equal(saved.state.status,'draft');assert.equal(saved.state.indexable,false);const events=await atlas.listEvents(workspace.id);assert.ok(events.some(event=>event.parentObjectId===saved.id&&event.type==='object.created'));const jobs=await repository.listIntelligenceJobs(workspace.id);assert.ok(jobs.some(job=>job.objectId===saved.id&&job.triggerType==='object.created'));const release=await builder.prepareRelease(workspace.id,saved.id,'usr_owner');assert.equal(release.type,'website_release_candidate');assert.equal(release.parentObjectId,saved.id);assert.equal(release.state.status,'pending_review');assert.equal(release.state.published,false);assert.equal(release.state.publicationRequiresHumanApproval,true);assert.equal((await builder.prepareRelease(workspace.id,saved.id,'usr_owner')).id,release.id);});

test('release preparation fails closed when content or identity gates remain unresolved',async()=>{const atlas=new AtlasService(new InMemoryRepository(),clock);const workspace=await atlas.createWorkspace({name:'Blocked Website Firm'});const builder=new WebsiteBuilderService(atlas,clock);const saved=await builder.save(workspace.id,{site:CRIMINAL_DEFENSE_TEMPLATE},'usr_owner');await assert.rejects(()=>builder.prepareRelease(workspace.id,saved.id,'usr_owner'),error=>error.code==='WEBSITE_SEO_NOT_READY'&&error.details.issues.length>=6);});

test('Atlas serves the editable builder and crawl-blocked multi-page public preview',async()=>{const atlas=new AtlasService(new InMemoryRepository(),clock);const handler=createAtlasHandler(atlas,{config:{maxBodyBytes:1_048_576,corsOrigins:[]},websiteBuilder:new WebsiteBuilderService(atlas,clock)});const editor=await get(handler,'/website-builder/');assert.equal(editor.status,200);assert.match(editor.text,/Atlas Website Builder/);const preview=await get(handler,'/website-preview/practice-areas/dui-defense/');assert.equal(preview.status,200);assert.match(preview.headers['content-security-policy'],/nonce-/);assert.match(preview.text,/DUI defense built around the evidence/);const robots=await get(handler,'/website-preview/robots.txt');assert.equal(robots.text,'User-agent: *\nDisallow: /\n');const missing=await get(handler,'/website-preview/not-a-page/');assert.equal(missing.status,404);});
