import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRepository } from '../src/repository.js';
import { AtlasService } from '../src/service.js';
import { CRIMINAL_DEFENSE_TEMPLATE, WebsiteBuilderService } from '../src/website-builder.js';
import { WebsiteOptimizationService, applyWebsiteSeoPatch, websiteInteractionContract } from '../src/website-optimization.js';

const clock=()=> '2026-07-14T22:00:00.000Z';
const copy=value=>JSON.parse(JSON.stringify(value));

function firmSite(){const site=copy(CRIMINAL_DEFENSE_TEMPLATE);site.firm={...site.firm,name:'Meridian Defense',shortName:'Meridian',phone:'(813) 555-0199',email:'intake@meridian.example',domain:'https://meridian.example',attorneyName:'Alex Morgan',attorneyVerified:true,officeVerified:true};site.pages=site.pages.map(page=>({...page,author:'Alex Morgan',localEvidenceVerified:page.type==='location'?true:page.localEvidenceVerified}));return site;}

test('aggregate performance ingestion blocks personal visitor data and computes the consultation funnel',async()=>{const atlas=new AtlasService(new InMemoryRepository(),clock);const workspace=await atlas.createWorkspace({name:'SEO Firm'});const site=await new WebsiteBuilderService(atlas,clock).save(workspace.id,{site:firmSite()},'usr_owner');const optimizer=new WebsiteOptimizationService(atlas,{clock,minPageViews:2});await optimizer.record(workspace.id,site.id,{eventType:'page_view',path:'/',source:'search',count:2},'analytics');await optimizer.record(workspace.id,site.id,{eventType:'consultation_scheduled',path:'/',source:'search'},'analytics');const summary=await optimizer.summary(workspace.id,site.id);assert.equal(summary.totals.pageViews,2);assert.equal(summary.totals.consultationScheduled,1);assert.equal(summary.conversionRate,.5);assert.equal(summary.eligibleForAnalysis,true);assert.equal(summary.personalDataStored,false);await assert.rejects(()=>optimizer.record(workspace.id,site.id,{eventType:'page_view',path:'/',source:'search',email:'visitor@example.com'},'analytics'),error=>error.code==='WEBSITE_PERFORMANCE_PERSONAL_DATA_BLOCKED');});

test('AI optimization is provider-neutral, evidence-gated, canonical, and approval-gated',async()=>{const repository=new InMemoryRepository();const atlas=new AtlasService(repository,clock);const workspace=await atlas.createWorkspace({name:'SEO Firm'});const site=await new WebsiteBuilderService(atlas,clock).save(workspace.id,{site:firmSite()},'usr_owner');const provider={async propose(){return{title:'Improve DUI search relevance',hypothesis:'A clearer evidence-focused description may improve qualified consultation starts.',confidence:.72,provider:'test-provider',model:'test-model',changes:[{path:'/practice-areas/dui-defense/',fields:{seoTitle:'Florida DUI Evidence Defense Lawyer | Meridian Defense',metaDescription:'Review Florida DUI stops, video, testing records, license issues, and defense planning with Meridian Defense.'},rationale:'Search arrivals are not starting consultations.'}]};}};const optimizer=new WebsiteOptimizationService(atlas,{clock,minPageViews:2,provider});await assert.rejects(()=>optimizer.propose(workspace.id,site.id,'usr_owner'),error=>error.code==='WEBSITE_OPTIMIZATION_INSUFFICIENT_EVIDENCE');await optimizer.record(workspace.id,site.id,{eventType:'page_view',path:'/practice-areas/dui-defense/',source:'search',count:25},'analytics');const proposal=await optimizer.propose(workspace.id,site.id,'usr_owner');assert.equal(proposal.type,'website_optimization_proposal');assert.equal(proposal.state.status,'pending_review');assert.equal(proposal.state.automaticPublication,false);assert.equal(proposal.state.provider,'test-provider');await assert.rejects(()=>optimizer.decide(workspace.id,proposal.id,{decision:'approved'},'usr_owner'),error=>error.code==='WEBSITE_OPTIMIZATION_REVIEW_REQUIRED');const release=await optimizer.decide(workspace.id,proposal.id,{decision:'approved',attorneyAdvertisingRulesReviewed:true},'usr_owner');assert.equal(release.type,'website_release_candidate');assert.equal(release.state.status,'pending_final_review');assert.equal(release.state.published,false);assert.equal(release.state.zeroDowntimeStrategy,'immutable_version_atomic_pointer_swap');assert.equal(release.state.rollbackSupported,true);assert.equal(release.state.siteSnapshot.pages.find(page=>page.path==='/practice-areas/dui-defense/').seoTitle,'Florida DUI Evidence Defense Lawyer | Meridian Defense');});

test('SEO patches cannot modify the protected interaction contract',()=>{const site=firmSite();const before=websiteInteractionContract(site);const updated=applyWebsiteSeoPatch(site,[{path:'/',fields:{seoTitle:'A better lawful title'}}]);assert.deepEqual(websiteInteractionContract(updated),before);assert.throws(()=>applyWebsiteSeoPatch(site,[{path:'/',fields:{phone:'(555) 000-0000'}}]),error=>error.code==='WEBSITE_OPTIMIZATION_INTERACTION_CHANGE_BLOCKED');assert.throws(()=>applyWebsiteSeoPatch(site,[{path:'/new-path/',fields:{seoTitle:'Unknown route'}}]),error=>error.code==='WEBSITE_OPTIMIZATION_PATCH_INVALID');});
