import { AtlasError, required } from './errors.js';
import { ProviderRegistry } from './accounting.js';

const eventTypes=new Set(['arrests','dissolution_petitions','car_accidents']);
const channels=new Set(['facebook','instagram','linkedin','google']);
const prohibitedPersonalKeys=/(^|_)(name|first_name|last_name|full_name|address|street|email|phone|dob|birth|ssn|license|person|defendant|petitioner|respondent|driver|victim|arrestee|case_number|docket_number)($|_)/i;

const clean=(value,field,max=500)=>{const text=String(required(value,field)).trim();if(!text||text.length>max)throw new AtlasError('MARKETING_INPUT_INVALID',`${field} is invalid`,400,{field});return text;};
const list=(value,field,allowed,max=10)=>{const values=[...new Set((Array.isArray(value)?value:[]).map(item=>String(item).trim().toLowerCase()).filter(Boolean))];if(!values.length||values.length>max||values.some(item=>!allowed.has(item)))throw new AtlasError('MARKETING_INPUT_INVALID',`${field} contains an unsupported value`,400,{field});return values;};
const date=(value,field,fallback)=>{const parsed=new Date(value??fallback);if(Number.isNaN(parsed.getTime()))throw new AtlasError('MARKETING_INPUT_INVALID',`${field} must be a valid date`,400,{field});return parsed.toISOString();};
const httpsUrl=(value,field,optional=false)=>{if(optional&&!value)return null;let parsed;try{parsed=new URL(value);}catch{throw new AtlasError('MARKETING_INPUT_INVALID',`${field} must be a valid HTTPS URL`,400,{field});}if(parsed.protocol!=='https:'||parsed.username||parsed.password)throw new AtlasError('MARKETING_INPUT_INVALID',`${field} must be a valid HTTPS URL`,400,{field});return parsed.toString();};
const money=(value,field='budgetMinor')=>{const amount=Number(value);if(!Number.isSafeInteger(amount)||amount<100)throw new AtlasError('MARKETING_INPUT_INVALID',`${field} must be at least 100 in the currency's smallest unit`,400,{field});return amount;};
const assertAggregateOnly=(value,path='record')=>{if(value==null||typeof value!=='object')return;for(const [key,nested] of Object.entries(value)){if(prohibitedPersonalKeys.test(key))throw new AtlasError('MARKETING_SOURCE_PERSONAL_DATA_BLOCKED','Public marketing sources must return aggregate data without person or case identifiers',422,{field:`${path}.${key}`});assertAggregateOnly(nested,`${path}.${key}`);}};

export const marketingSourceCatalog=Object.freeze([
  {eventType:'arrests',label:'Arrest activity',scope:'aggregate_only',startingSource:'FBI Uniform Crime Reporting and approved jurisdiction open-data sources',personLevelUse:false},
  {eventType:'dissolution_petitions',label:'Dissolution petition activity',scope:'aggregate_only',startingSource:'Approved state or local court aggregate filing feeds',personLevelUse:false},
  {eventType:'car_accidents',label:'Car-accident activity',scope:'aggregate_only',startingSource:'NHTSA FARS and approved state crash-data sources',personLevelUse:false}
]);

export class HttpAggregatePublicSource{
  constructor(options={}){this.name=clean(options.name,'name',120);this.label=clean(options.label??options.name,'label',160);this.eventType=clean(options.eventType,'eventType',80);if(!eventTypes.has(this.eventType))throw new AtlasError('MARKETING_SOURCE_INVALID','Public source eventType is unsupported',500);this.endpoint=httpsUrl(options.endpoint,'endpoint');this.jurisdiction=String(options.jurisdiction??'').trim()||null;this.transport=options.transport??fetch;}
  describe(){return{label:this.label,eventType:this.eventType,jurisdiction:this.jurisdiction,aggregateOnly:true,personLevelUse:false,configured:true};}
  async fetchTrends(input={}){if(this.jurisdiction&&this.jurisdiction.toLowerCase()!==String(input.jurisdiction??'').trim().toLowerCase())throw new AtlasError('MARKETING_SOURCE_JURISDICTION_UNAVAILABLE',`${this.label} is not configured for the selected jurisdiction`,409,{source:this.name,jurisdiction:this.jurisdiction});const url=new URL(this.endpoint);url.searchParams.set('from',input.from);url.searchParams.set('to',input.to);url.searchParams.set('jurisdiction',input.jurisdiction);let response;try{response=await this.transport(url.toString(),{headers:{accept:'application/json'}});}catch{throw new AtlasError('MARKETING_SOURCE_UNAVAILABLE',`${this.label} is unavailable`,503,{source:this.name});}if(!response.ok)throw new AtlasError('MARKETING_SOURCE_UNAVAILABLE',`${this.label} returned an error`,503,{source:this.name,status:response.status});let body;try{body=await response.json();}catch{throw new AtlasError('MARKETING_SOURCE_INVALID',`${this.label} returned invalid JSON`,502,{source:this.name});}const rows=Array.isArray(body)?body:Array.isArray(body?.results)?body.results:null;if(!rows||rows.length>500)throw new AtlasError('MARKETING_SOURCE_INVALID',`${this.label} must return no more than 500 aggregate rows`,502,{source:this.name});return rows.map((row,index)=>{assertAggregateOnly(row,`results[${index}]`);const count=Number(row.count);if(!Number.isSafeInteger(count)||count<0)throw new AtlasError('MARKETING_SOURCE_INVALID',`${this.label} returned an invalid aggregate count`,502,{source:this.name,index});const observedAt=date(row.date??row.observedAt,'date',input.to);const jurisdiction=clean(row.jurisdiction??input.jurisdiction,'jurisdiction',160);if(jurisdiction.toLowerCase()!==String(input.jurisdiction).trim().toLowerCase())throw new AtlasError('MARKETING_SOURCE_INVALID',`${this.label} returned data for a different jurisdiction`,502,{source:this.name,index});return{count,observedAt,jurisdiction,sourceUrl:httpsUrl(row.sourceUrl??this.endpoint,'sourceUrl'),sourceName:this.label};});}
}

export class MarketingService{
  constructor(atlas,options={}){this.atlas=atlas;this.publicSources=options.publicSources??new ProviderRegistry('Marketing public data');this.adProviders=options.adProviders??new ProviderRegistry('Advertising');this.clock=options.clock??atlas.clock??(()=>new Date().toISOString());}
  availableAdProviders(workspaceId){return this.adProviders.list().filter(item=>{try{const provider=this.adProviders.resolve(item.name);return typeof provider.availableFor==='function'&&provider.availableFor(workspaceId);}catch{return false;}}).map(({workspaceId:ignored,...item})=>item);}
  async status(workspaceId){const objects=await this.atlas.listObjects(workspaceId,{dimension:'operation'});const publicSources=this.publicSources.list();return{sourceCatalog:marketingSourceCatalog.map(item=>({...item,configured:publicSources.some(source=>source.eventType===item.eventType)})),publicSources,adProviders:this.availableAdProviders(workspaceId),campaigns:objects.filter(item=>item.type==='marketing_campaign').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),signals:objects.filter(item=>item.type==='public_market_signal').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),launches:objects.filter(item=>item.type==='marketing_campaign_launch').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))};}
  sourcesFor(eventType){return this.publicSources.list().filter(item=>item.eventType===eventType).map(item=>({descriptor:item,provider:this.publicSources.resolve(item.name)}));}
  async scan(workspaceId,input,actorId){const requested=list(input.eventTypes,'eventTypes',eventTypes,3);const jurisdiction=clean(input.jurisdiction,'jurisdiction',160);const to=date(input.to,'to',this.clock());const from=date(input.from,'from',new Date(new Date(to).getTime()-30*86400000));const days=(new Date(to)-new Date(from))/86400000;if(days<0||days>366)throw new AtlasError('MARKETING_INPUT_INVALID','The public-data date range must be between 0 and 366 days',400);const fetched=[];const missing=[];for(const eventType of requested){const sources=this.sourcesFor(eventType);if(!sources.length){missing.push(eventType);continue;}for(const {descriptor,provider} of sources){const rows=await provider.fetchTrends({workspaceId,eventType,jurisdiction,from,to});for(const row of rows){assertAggregateOnly(row);fetched.push({...row,eventType,sourceName:row.sourceName??descriptor.label,sourceProvider:descriptor.name});}}}if(!fetched.length)throw new AtlasError('MARKETING_PUBLIC_SOURCES_NOT_CONFIGURED','Connect an approved aggregate public-data source for the selected jurisdiction',409,{eventTypes:requested,missing});const scan=await this.atlas.createObject(workspaceId,{dimension:'operation',type:'marketing_public_scan',title:`Public market scan — ${jurisdiction}`,actorId,state:{jurisdiction,from,to,eventTypes:requested,missingEventTypes:missing,aggregateOnly:true,personalRecordsStored:false,personLevelTargeting:false,scannedAt:this.clock()}});const signals=[];for(const eventType of requested){const rows=fetched.filter(row=>row.eventType===eventType);if(!rows.length)continue;const signal=await this.atlas.createObject(workspaceId,{parentObjectId:scan.id,dimension:'operation',type:'public_market_signal',title:`${marketingSourceCatalog.find(item=>item.eventType===eventType).label} — ${jurisdiction}`,actorId,state:{eventType,jurisdiction,from,to,count:rows.reduce((sum,row)=>sum+row.count,0),sources:[...new Set(rows.map(row=>row.sourceName))],sourceUrls:[...new Set(rows.map(row=>row.sourceUrl))],observations:rows.length,aggregateOnly:true,personalRecordsStored:false,eligibleForNamedOutreach:false,eligibleForPersonalizedTargeting:false}});signals.push(signal);}return{scan,signals,missingEventTypes:missing};}
  async createCampaign(workspaceId,input,actorId){const selectedChannels=list(input.channels,'channels',channels,4);const title=clean(input.title,'title',240);const practiceArea=clean(input.practiceArea,'practiceArea',200);const geography=clean(input.geography,'geography',200);if(/\bzip\b|\bpostal\b|\baddress\b/i.test(geography))throw new AtlasError('MARKETING_TARGETING_RESTRICTED','Use city, county, state, or a broad radius instead of address or ZIP-level targeting',400);const radiusMiles=Number(input.radiusMiles??25);if(!Number.isFinite(radiusMiles)||radiusMiles<10||radiusMiles>500)throw new AtlasError('MARKETING_TARGETING_RESTRICTED','Geographic radius must be between 10 and 500 miles',400);for(const field of ['names','emails','phones','customAudience','recordIds','caseNumbers'])if(input[field]?.length)throw new AtlasError('MARKETING_TARGETING_RESTRICTED','Named people and public-record identities cannot be used as an advertising audience',400,{field});const headline=clean(input.headline,'headline',120);const body=clean(input.body,'body',2000);const landingPage=httpsUrl(input.landingPage,'landingPage');const startAt=date(input.startAt,'startAt',this.clock());const endAt=date(input.endAt,'endAt',new Date(new Date(startAt).getTime()+30*86400000));if(new Date(endAt)<=new Date(startAt))throw new AtlasError('MARKETING_INPUT_INVALID','endAt must be after startAt',400,{field:'endAt'});const sourceSignalIds=[...new Set(Array.isArray(input.sourceSignalIds)?input.sourceSignalIds:[])];for(const id of sourceSignalIds){const signal=await this.atlas.getObject(workspaceId,id);if(signal.type!=='public_market_signal'||signal.state?.aggregateOnly!==true)throw new AtlasError('MARKETING_INPUT_INVALID','sourceSignalIds must identify aggregate Atlas marketing signals',400);}return this.atlas.createObject(workspaceId,{dimension:'operation',type:'marketing_campaign',title,actorId,state:{practiceArea,channels:selectedChannels,budgetMinor:money(input.budgetMinor),currency:'USD',startAt,endAt,creative:{headline,body,callToAction:String(input.callToAction??'Learn more').trim().slice(0,80),landingPage},targeting:{mode:'broad_geographic',geography,radiusMiles,minimumAudienceSize:1000,personalizedSensitiveTargeting:false,namedPublicRecordAudience:false},sourceSignalIds,status:'draft',externalPublishing:false,requiresAttorneyApproval:true,requiresAdvertisingRuleReview:true,automaticContact:false,createdBy:actorId}});}
  providerForChannel(channel,workspaceId){const match=this.availableAdProviders(workspaceId).find(item=>Array.isArray(item.channels)&&item.channels.includes(channel));if(!match)throw new AtlasError('MARKETING_AD_PROVIDER_NOT_CONFIGURED',`No firm-connected advertising provider supports ${channel}`,409,{channel});return{name:match.name,provider:this.adProviders.resolve(match.name)};}
  async prepareCampaign(workspaceId,campaignId,input,actorId){const campaign=await this.atlas.getObject(workspaceId,campaignId);if(campaign.type!=='marketing_campaign')throw new AtlasError('MARKETING_INPUT_INVALID','campaignId must identify a marketing campaign',400);if(campaign.state?.status!=='draft')throw new AtlasError('MARKETING_CAMPAIGN_STATE_INVALID','Only a draft campaign can be prepared',409);for(const field of ['attorneyAdvertisingRulesReviewed','platformPoliciesReviewed','landingPageReviewed'])if(input[field]!==true)throw new AtlasError('MARKETING_REVIEW_REQUIRED','Attorney advertising rules, platform policies, and the landing page must all be reviewed',409,{field});const grouped=new Map();for(const channel of campaign.state.channels){const connection=this.providerForChannel(channel,workspaceId);const current=grouped.get(connection.name)??{...connection,channels:[]};current.channels.push(channel);grouped.set(connection.name,current);}const prepared=[];for(const entry of grouped.values()){if(typeof entry.provider.createPausedCampaign!=='function')throw new AtlasError('MARKETING_AD_PROVIDER_INVALID','Advertising provider cannot create a paused campaign',503,{provider:entry.name});const external=await entry.provider.createPausedCampaign({workspaceId,campaign,channels:entry.channels});if(!external?.externalId)throw new AtlasError('MARKETING_AD_PROVIDER_INVALID','Advertising provider returned no campaign ID',502,{provider:entry.name});const launch=await this.atlas.createObject(workspaceId,{parentObjectId:campaign.id,dimension:'operation',type:'marketing_campaign_launch',title:`${campaign.title} — ${entry.name}`,actorId,state:{campaignId:campaign.id,provider:entry.name,channels:entry.channels,externalId:String(external.externalId),status:'paused',managementUrl:httpsUrl(external.managementUrl,'managementUrl',true),createdPaused:true,activatedByAtlas:false,preparedAt:this.clock(),reviewedBy:actorId}});prepared.push(launch);}const updated=await this.atlas.updateObject(workspaceId,campaign.id,{version:campaign.version,state:{...campaign.state,status:'provider_review',externalPublishing:false,preparedAt:this.clock(),reviewedBy:actorId,reviewAttestations:{attorneyAdvertisingRulesReviewed:true,platformPoliciesReviewed:true,landingPageReviewed:true}}},actorId);return{campaign:updated,launches:prepared};}
}

export { ProviderRegistry as MarketingProviderRegistry };
