import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { AtlasError } from './errors.js';
import { createId } from './ids.js';

const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function base32Encode(value){let bits=0,buffer=0,output='';for(const byte of value){buffer=(buffer<<8)|byte;bits+=8;while(bits>=5){output+=alphabet[(buffer>>>(bits-5))&31];bits-=5;}}if(bits)output+=alphabet[(buffer<<(5-bits))&31];return output;}
function base32Decode(value){let bits=0,buffer=0;const output=[];for(const character of String(value).replace(/=|\s|-/g,'').toUpperCase()){const index=alphabet.indexOf(character);if(index<0)throw new AtlasError('MFA_SECRET_INVALID','MFA secret is invalid',500);buffer=(buffer<<5)|index;bits+=5;if(bits>=8){output.push((buffer>>>(bits-8))&255);bits-=8;}}return Buffer.from(output);}
function normalizeCode(value){return String(value??'').toUpperCase().replace(/[^A-Z0-9]/g,'');}
function hashRecovery(userId,value){return createHash('sha256').update(`${userId}:${normalizeCode(value)}`).digest('hex');}
function constantEqual(left,right){const a=Buffer.from(String(left));const b=Buffer.from(String(right));return a.length===b.length&&timingSafeEqual(a,b);}
function hotp(secret,counter,digits=6){const value=Buffer.alloc(8);value.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',secret).update(value).digest();const offset=digest[digest.length-1]&15;const number=(digest.readUInt32BE(offset)&0x7fffffff)%(10**digits);return String(number).padStart(digits,'0');}
export function totp(secret,time=Date.now(),stepSeconds=30){return hotp(base32Decode(secret),Math.floor(time/1000/stepSeconds));}

export class MfaService{
  constructor(repository,options={}){this.repository=repository;this.clock=options.clock??(()=>new Date().toISOString());this.nowMs=options.nowMs??(()=>Date.now());this.randomBytes=options.randomBytes??randomBytes;this.key=createHash('sha256').update(String(options.encryptionSecret??'')).digest();this.issuer=options.issuer??'Atlas';}
  encrypt(secret){const iv=this.randomBytes(12);const cipher=createCipheriv('aes-256-gcm',this.key,iv);const encrypted=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return `v1:${iv.toString('base64url')}:${encrypted.toString('base64url')}:${cipher.getAuthTag().toString('base64url')}`;}
  decrypt(envelope){const [version,iv,ciphertext,tag]=String(envelope).split(':');if(version!=='v1')throw new AtlasError('MFA_SECRET_INVALID','MFA secret cannot be decrypted',500);try{const decipher=createDecipheriv('aes-256-gcm',this.key,Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(ciphertext,'base64url')),decipher.final()]).toString('utf8');}catch{throw new AtlasError('MFA_SECRET_INVALID','MFA secret cannot be decrypted',500);}}
  recoveryCodes(userId){return Array.from({length:10},()=>{const raw=this.randomBytes(8).toString('hex').toUpperCase();return `${raw.slice(0,4)}-${raw.slice(4,8)}-${raw.slice(8,12)}-${raw.slice(12,16)}`;});}
  async status(userId){let factor;try{factor=await this.repository.getMfaFactor(userId);}catch(error){if(error.code==='MFA_NOT_CONFIGURED')return {enabled:false,pending:false};throw error;}return {enabled:factor.enabled,pending:!factor.enabled,verifiedAt:factor.verifiedAt??null,recoveryCodesRemaining:factor.recoveryCodeHashes.length};}
  async begin(user){const secret=base32Encode(this.randomBytes(20));const codes=this.recoveryCodes(user.id);const now=this.clock();await this.repository.upsertMfaFactor({userId:user.id,encryptedSecret:this.encrypt(secret),enabled:false,recoveryCodeHashes:codes.map(code=>hashRecovery(user.id,code)),createdAt:now,verifiedAt:null,updatedAt:now});const label=encodeURIComponent(`${this.issuer}:${user.email}`);const issuer=encodeURIComponent(this.issuer);return {secret,otpauthUri:`otpauth://totp/${label}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`,recoveryCodes:codes};}
  verifyTotp(secret,code){const normalized=normalizeCode(code);if(!/^\d{6}$/.test(normalized))return false;const counter=Math.floor(this.nowMs()/1000/30);return [-1,0,1].some(offset=>constantEqual(hotp(base32Decode(secret),counter+offset),normalized));}
  async verify(userId,code,{consumeRecovery=true,requireEnabled=true}={}){const factor=await this.repository.getMfaFactor(userId);if(requireEnabled&&!factor.enabled)throw new AtlasError('MFA_NOT_ENABLED','Multi-factor authentication is not enabled',409);const secret=this.decrypt(factor.encryptedSecret);if(this.verifyTotp(secret,code))return {method:'totp'};const recoveryHash=hashRecovery(userId,code);const index=factor.recoveryCodeHashes.findIndex(value=>constantEqual(value,recoveryHash));if(index<0)throw new AtlasError('MFA_CODE_INVALID','The authentication code is invalid',401);if(!consumeRecovery)throw new AtlasError('MFA_CODE_INVALID','Use an authenticator code to confirm enrollment',401);const remaining=factor.recoveryCodeHashes.filter((_,position)=>position!==index);await this.repository.upsertMfaFactor({...factor,recoveryCodeHashes:remaining,updatedAt:this.clock()});return {method:'recovery_code'};}
  async confirm(userId,code){const factor=await this.repository.getMfaFactor(userId);if(factor.enabled)throw new AtlasError('MFA_ALREADY_ENABLED','Multi-factor authentication is already enabled',409);await this.verify(userId,code,{consumeRecovery:false,requireEnabled:false});const now=this.clock();await this.repository.upsertMfaFactor({...factor,enabled:true,verifiedAt:now,updatedAt:now});return {enabled:true,recoveryCodesRemaining:factor.recoveryCodeHashes.length};}
  async disable(userId,code){await this.verify(userId,code);await this.repository.deleteMfaFactor(userId);return {enabled:false};}
}
