import { randomBytes } from 'node:crypto';

async function responseData(response,label){let body;try{body=await response.json();}catch{throw new Error(`${label} returned invalid JSON`);}if(!response.ok)throw new Error(`${label} failed with status ${response.status}: ${body.error?.code??'UNKNOWN'}`);return body.data;}
export async function runStagingSmoke(baseUrl,options={}){const base=String(baseUrl??'').replace(/\/$/,'');if(!base)throw new Error('STAGING_BASE_URL is required');const parsed=new URL(base);if(parsed.protocol!=='https:'&&!['127.0.0.1','localhost'].includes(parsed.hostname))throw new Error('STAGING_BASE_URL must use HTTPS outside localhost');const transport=options.transport??fetch;const suffix=(options.randomBytes??randomBytes)(8).toString('hex');const email=`atlas-smoke-${suffix}@example.invalid`;const password=(options.password??`Atlas-smoke-${suffix}-secure-password`);const started=Date.now();const checks=[];
  const ready=await responseData(await transport(`${base}/ready`),'readiness');if(ready.status!=='ready')throw new Error('Atlas did not report ready');checks.push('ready');
  const page=await transport(`${base}/`);const html=await page.text();if(!page.ok||!html.includes('Atlas')||!html.includes('While You Were Gone'))throw new Error('Connected homepage smoke check failed');checks.push('homepage');
  const registered=await responseData(await transport(`${base}/v1/auth/register`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,name:'Atlas Smoke Test',password})}),'registration');if(!registered.accessToken||!registered.user?.id)throw new Error('Registration did not return an authenticated user');checks.push('authentication');
  const auth={authorization:`Bearer ${registered.accessToken}`,'content-type':'application/json'};const workspace=await responseData(await transport(`${base}/v1/workspaces`,{method:'POST',headers:auth,body:JSON.stringify({name:`Atlas Smoke ${suffix}`})}),'workspace creation');if(!workspace.id)throw new Error('Workspace creation did not return an ID');checks.push('workspace');
  const feed=await responseData(await transport(`${base}/v1/workspaces/${encodeURIComponent(workspace.id)}/home/while-you-were-gone`,{headers:{authorization:auth.authorization}}),'awareness feed');if(!Array.isArray(feed))throw new Error('Awareness feed did not return a list');checks.push('awareness');
  return {passed:true,checks,durationMs:Date.now()-started,version:ready.version??null,workspaceCreated:true};
}
