import { AtlasError } from './errors.js';
import { createId } from './ids.js';
import { timingSafeEqual } from 'node:crypto';

const text=(value,max,name,{requiredValue=false}={})=>{const result=String(value??'').trim();if(requiredValue&&!result)throw new AtlasError('WEBSITE_INTAKE_INVALID',`${name} is required`,400);if(result.length>max)throw new AtlasError('WEBSITE_INTAKE_INVALID',`${name} is too long`,400);return result||null;};
const bearer=value=>{const match=String(value??'').match(/^Bearer\s+(.+)$/i);return match?.[1]??null;};
const sameSecret=(left,right)=>{const a=Buffer.from(String(left??''));const b=Buffer.from(String(right??''));return a.length===b.length&&a.length>0&&timingSafeEqual(a,b);};
const phone=value=>String(value??'').replace(/[^+\d]/g,'');
const affirmative=value=>/^(yes|y|confirm|confirmed|accept|accepted|ok|okay)$/i.test(String(value??'').trim());

function localParts(date,timeZone){const parts=new Intl.DateTimeFormat('en-US',{timeZone,weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);return Object.fromEntries(parts.map(part=>[part.type,part.value]));}
function overlaps(start,end,event){const eventStart=new Date(event.state?.startsAt??event.state?.start).getTime();const eventEnd=new Date(event.state?.endsAt??event.state?.end).getTime();return Number.isFinite(eventStart)&&Number.isFinite(eventEnd)&&start<eventEnd&&end>eventStart;}
function formatted(slot){return new Intl.DateTimeFormat('en-US',{timeZone:slot.timeZone,dateStyle:'full',timeStyle:'short'}).format(new Date(slot.startsAt));}
function delivery(status='pending',reason=null,extra={}){return{status,reason,...extra};}
function publicRequest(object){return{id:object.id,title:object.title,status:object.state.status,version:object.version,receivedAt:object.state.receivedAt,prospectiveClient:{name:object.state.prospectiveClient.name,number:object.state.prospectiveClient.number},matterSummary:object.state.matterSummary,consultation:object.state.consultation,proposedSlots:object.state.proposedSlots,selectedSlot:object.state.selectedSlot??null,negotiationRound:object.state.negotiationRound??0,clientCounterMessage:object.state.clientCounterMessage??null,calendarEventId:object.state.calendarEventId??null,attorneySmsDelivery:object.state.attorneySmsDelivery??null,clientProposalSmsDelivery:object.state.clientProposalSmsDelivery??null,clientSmsDelivery:object.state.clientSmsDelivery??null,calendarDelivery:object.state.calendarDelivery??null};}

export class WebsiteIntakeService {
  constructor(atlas,repository,options={}){this.atlas=atlas;this.repository=repository;this.clock=options.clock??(()=>new Date().toISOString());this.attorneySmsSender=options.attorneySmsSender??null;this.clientSmsSender=options.clientSmsSender??null;this.connections=new Map((options.connections??[]).map(item=>[item.websiteId,item]));}
  connection(websiteId,authorization){const connection=this.connections.get(websiteId);if(!connection||!sameSecret(bearer(authorization),connection.token))throw new AtlasError('WEBSITE_INTAKE_UNAUTHORIZED','Website intake credentials are invalid',401);return connection;}
  connectionForWorkspace(workspaceId){return [...this.connections.values()].find(item=>item.workspaceId===workspaceId)??null;}
  async proposedSlots(connection,{durationMinutes=30,limit=3}={}){const events=(await this.atlas.listObjects(connection.workspaceId,{type:'calendar_event'})).filter(item=>!item.deletedAt);const slots=[];let cursor=Math.ceil((new Date(this.clock()).getTime()+60*60*1000)/(30*60*1000))*(30*60*1000);const end=cursor+21*24*60*60*1000;while(cursor<end&&slots.length<limit){const start=new Date(cursor);const parts=localParts(start,connection.timeZone);const hour=Number(parts.hour);const minute=Number(parts.minute);const duration=durationMinutes*60*1000;const finish=cursor+duration;const workday=!['Sat','Sun'].includes(parts.weekday)&&hour>=9&&(hour<16||(hour===16&&minute===0));if(workday&&!events.some(event=>overlaps(cursor,finish,event)))slots.push({startsAt:start.toISOString(),endsAt:new Date(finish).toISOString(),timeZone:connection.timeZone});cursor+=30*60*1000;}if(slots.length<limit)throw new AtlasError('CONSULTATION_AVAILABILITY_UNAVAILABLE','Atlas could not identify enough open calendar times',503);return slots;}
  async slotAvailable(workspaceId,slot){const start=new Date(slot.startsAt).getTime();const end=new Date(slot.endsAt).getTime();if(!Number.isFinite(start)||!Number.isFinite(end)||start<=new Date(this.clock()).getTime()||end<=start)return false;const events=(await this.atlas.listObjects(workspaceId,{type:'calendar_event'})).filter(item=>!item.deletedAt);return !events.some(event=>overlaps(start,end,event));}
  normalize(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new AtlasError('WEBSITE_INTAKE_INVALID','Consultation request must be an object',400);const name=text(input.name,200,'name',{requiredValue:true});const number=text(input.phone??input.contactNumber,80,'contact number',{requiredValue:true});if(input.consent!==true)throw new AtlasError('WEBSITE_INTAKE_INVALID','contact permission is required',400);if(input.textConsent!==true)throw new AtlasError('WEBSITE_INTAKE_INVALID','scheduling text permission is required',400);return{name,number,textConsent:true,matterType:text(input.matterType,160,'matter type'),charges:text(input.charges,240,'charge'),location:text(input.location,240,'location'),caseNumber:text(input.caseNumber,120,'case number'),message:text(input.message,4000,'message',{requiredValue:true}),page:text(input.page,500,'page'),consultationType:text(input.consultationType,40,'consultation type')??'standard',receivedAt:this.clock()};}
  async notifyAttorneyOfRequest(request){const slots=request.state.proposedSlots;const optionText=slots.map((slot,index)=>`${index+1}) ${formatted(slot)}`).join('; ');let smsDelivery=delivery('pending','sms_sender_not_configured');if(this.attorneySmsSender){try{const sent=await this.attorneySmsSender({workspaceId:request.workspaceId,targetUserId:request.state.targetUserId,requestId:request.id,prospectiveClient:request.state.prospectiveClient,proposedSlots:slots,timeZone:slots[0].timeZone,body:`Atlas: ${request.state.prospectiveClient.name} requested a consultation. ${optionText}. Reply 1, 2, or 3 to send that proposed time to the prospective client. No appointment is scheduled yet.`});smsDelivery=delivery(sent.message?.state?.status??sent.status??'sent',null,{provider:sent.message?.state?.provider??sent.provider??null,draftId:sent.draft?.id??null,messageId:sent.message?.id??null});}catch(error){smsDelivery=delivery('pending',error.code??'SMS_DELIVERY_FAILED');}}
    return{attorneySmsDelivery:smsDelivery};
  }
  async notifyAttorneyDirect(request,{smsBody}){let smsDelivery=delivery('pending','sms_sender_not_configured');if(this.attorneySmsSender){try{const sent=await this.attorneySmsSender({workspaceId:request.workspaceId,targetUserId:request.state.targetUserId,requestId:request.id,prospectiveClient:request.state.prospectiveClient,proposedSlots:request.state.proposedSlots,timeZone:request.state.proposedSlots?.[0]?.timeZone??'America/New_York',body:smsBody});smsDelivery=delivery(sent.message?.state?.status??sent.status??'sent',null,{provider:sent.message?.state?.provider??sent.provider??null,messageId:sent.message?.id??null});}catch(error){smsDelivery=delivery('pending',error.code??'SMS_DELIVERY_FAILED');}}return{smsDelivery};}
  async availability(websiteId,authorization){const connection=this.connection(websiteId,authorization);return{websiteId,status:'attorney_confirmation_required',slots:await this.proposedSlots(connection)};}
  async ingest(websiteId,authorization,input){const connection=this.connection(websiteId,authorization);const intake=this.normalize(input);const duration=intake.consultationType==='immediate'?20:30;const proposedSlots=await this.proposedSlots(connection,{durationMinutes:duration});let request=await this.atlas.createObject(connection.workspaceId,{dimension:'operation',type:'website_consultation_request',title:`Consultation request — ${intake.name}`,actorId:`website:${websiteId}`,state:{scope:'firm',websiteId,status:'pending_attorney_confirmation',receivedAt:intake.receivedAt,targetUserId:connection.targetUserId,prospectiveClient:{name:intake.name,number:intake.number,textConsent:true,textConsentedAt:intake.receivedAt},matterSummary:{matterType:intake.matterType,charges:intake.charges,location:intake.location,caseNumber:intake.caseNumber,message:intake.message,sourcePage:intake.page},consultation:{type:intake.consultationType,durationMinutes:duration,attorneyWillContact:true,confirmationChannels:['sms'],maximumAttorneyProposals:2,deliveryMode:'direct_to_attorney'},proposedSlots,selectedSlot:null,negotiationRound:0,calendarEventId:null}});const notices=await this.notifyAttorneyOfRequest(request);request=await this.atlas.updateObject(connection.workspaceId,request.id,{version:request.version,state:{...request.state,...notices}},`website:${websiteId}`);return{requestId:request.id,status:request.state.status,proposedSlotCount:proposedSlots.length,attorneyConfirmationRequired:true,attorneySmsDelivery:notices.attorneySmsDelivery};}
  async list(workspaceId){return(await this.atlas.listObjects(workspaceId,{type:'website_consultation_request'})).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).map(publicRequest);}
  selectSlot(request,input){const matching=request.state.proposedSlots.find(slot=>slot.startsAt===input.startsAt&&slot.endsAt===input.endsAt);if(matching)return matching;const startsAt=new Date(input.startsAt).toISOString();const endsAt=new Date(input.endsAt).toISOString();const duration=(new Date(endsAt)-new Date(startsAt))/60000;if(!Number.isFinite(duration)||duration<10||duration>120)throw new AtlasError('CONSULTATION_SLOT_INVALID','Choose a valid consultation time lasting 10 to 120 minutes',400);return{startsAt,endsAt,timeZone:input.timeZone??request.state.proposedSlots[0]?.timeZone??'America/New_York'};}
  async approve(workspaceId,requestId,input,actorId){let request=await this.atlas.getObject(workspaceId,requestId);if(request.type!=='website_consultation_request')throw new AtlasError('CONSULTATION_REQUEST_NOT_FOUND','Consultation request not found',404);if(!['pending_attorney_confirmation','client_counter_received','slot_conflict_attorney_action'].includes(request.state.status))throw new AtlasError('CONSULTATION_REQUEST_NOT_AWAITING_ATTORNEY','This consultation is not awaiting an attorney time proposal',409);if(input.version!==request.version)throw new AtlasError('VERSION_CONFLICT','Consultation request version is stale',409,{currentVersion:request.version});const round=(request.state.negotiationRound??0)+1;if(round>2)throw new AtlasError('CONSULTATION_DIRECT_SCHEDULING_REQUIRED','The automated proposal limit has been reached; continue scheduling through the Atlas communication thread',409);const selected=this.selectSlot(request,input);if(!await this.slotAvailable(workspaceId,selected))throw new AtlasError('CONSULTATION_SLOT_UNAVAILABLE','That time is no longer open. Choose another time.',409);const when=formatted(selected);let smsDelivery=delivery('pending','sms_sender_not_configured');if(this.clientSmsSender){try{const sent=await this.clientSmsSender({workspaceId,targetUserId:actorId,requestId:request.id,to:request.state.prospectiveClient.number,textConsent:true,authorizationType:'client_consultation_proposal',body:`Florida’s Law Office: Would ${when} work for your consultation? Reply YES to confirm. If not, reply with a better date and time. No appointment is scheduled yet. Reply STOP to opt out.`});smsDelivery=delivery(sent.message?.state?.status??sent.status??'sent',null,{provider:sent.message?.state?.provider??sent.provider??null,draftId:sent.draft?.id??null,messageId:sent.message?.id??null});}catch(error){smsDelivery=delivery('pending',error.code??'SMS_DELIVERY_FAILED');}}
    request=await this.atlas.updateObject(workspaceId,request.id,{version:request.version,state:{...request.state,status:'awaiting_client_confirmation',selectedSlot:selected,negotiationRound:round,proposedBy:actorId,proposedAt:this.clock(),clientCounterMessage:null,clientProposalSmsDelivery:smsDelivery}},actorId);return{request:publicRequest(request),clientProposalSmsDelivery:smsDelivery};}
  async handleSmsReply(workspaceId,input){
    const body=String(input.body??'').trim();
    const all=(await this.atlas.listObjects(workspaceId,{type:'website_consultation_request'})).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));
    if(input.role==='attorney'){
      const request=all.find(item=>['pending_attorney_confirmation','client_counter_received','slot_conflict_attorney_action','direct_scheduling_open'].includes(item.state?.status));
      if(!request)return{handled:false};
      if(request.state.status==='direct_scheduling_open'){
        const messages=[...(request.state.directSchedulingMessages??[]),{body,receivedAt:this.clock(),channel:'sms',sender:'attorney'}].slice(-50);
        const updated=await this.atlas.updateObject(workspaceId,request.id,{version:request.version,state:{...request.state,directSchedulingMessages:messages,lastDirectSchedulingMessageAt:this.clock()}},'attorney:sms');
        let sent=null;
        if(this.clientSmsSender)sent=await this.clientSmsSender({workspaceId,targetUserId:request.state.targetUserId,requestId:request.id,to:request.state.prospectiveClient.number,textConsent:true,authorizationType:'client_consultation_scheduling',body:`Florida’s Law Office: ${body} Reply here to continue scheduling. Reply STOP to opt out.`});
        return{handled:true,reply:'Your message was sent directly to the prospective client.',request:publicRequest(updated),delivery:sent};
      }
      if(!/^[123]$/.test(body))return{handled:true,reply:'Reply 1, 2, or 3 to select one of the available consultation times.'};
      const slot=request.state.proposedSlots?.[Number(body)-1];
      if(!slot)return{handled:true,reply:'That option is no longer available. Atlas will text refreshed choices.'};
      const result=await this.approve(workspaceId,request.id,{version:request.version,startsAt:slot.startsAt,endsAt:slot.endsAt,timeZone:slot.timeZone},request.state.targetUserId);
      return{handled:true,reply:`Option ${body} was sent to ${request.state.prospectiveClient.name}. Atlas is waiting for their confirmation.`,result};
    }
    const number=phone(input.from);
    const request=all.find(item=>['awaiting_client_confirmation','direct_scheduling_open'].includes(item.state?.status)&&phone(item.state?.prospectiveClient?.number)===number);
    if(!request)return{handled:false};
    if(request.state.status==='direct_scheduling_open'){
      const messages=[...(request.state.directSchedulingMessages??[]),{body,receivedAt:this.clock(),channel:'sms',sender:'client'}].slice(-50);
      const updated=await this.atlas.updateObject(workspaceId,request.id,{version:request.version,state:{...request.state,directSchedulingMessages:messages,lastDirectSchedulingMessageAt:this.clock()}},'client:sms');
      await this.notifyAttorneyDirect(updated,{smsBody:`Atlas: ${updated.state.prospectiveClient.name} replied: “${body}” Reply to this text to continue scheduling directly.`});
      return{handled:true,reply:null,request:publicRequest(updated)};
    }
    if(affirmative(body))return{handled:true,reply:'Thank you. Atlas is confirming the appointment now.',result:await this.confirmClient(workspaceId,request.id,'client:sms')};
    const round=request.state.negotiationRound??1;
    const direct=round>=2;
    const status=direct?'direct_scheduling_open':'client_counter_received';
    let proposedSlots=request.state.proposedSlots;
    if(!direct){const connection=this.connectionForWorkspace(workspaceId);if(connection)proposedSlots=await this.proposedSlots(connection,{durationMinutes:request.state.consultation?.durationMinutes??30});}
    const updated=await this.atlas.updateObject(workspaceId,request.id,{version:request.version,state:{...request.state,status,proposedSlots,clientCounterMessage:body,clientCounterReceivedAt:this.clock()}},'client:sms');
    const options=direct?'':` New options: ${proposedSlots.map((slot,index)=>`${index+1}) ${formatted(slot)}`).join('; ')}. Reply 1, 2, or 3.`;
    await this.notifyAttorneyDirect(updated,{smsBody:`Atlas: ${updated.state.prospectiveClient.name} replied: “${body}”.${options}`});
    return{handled:true,reply:direct?'Thank you. Your message was sent directly to the attorney. Continue replying here to coordinate a time.':'Thank you. The attorney will review your requested time and either confirm it or propose one other time.',request:publicRequest(updated)};
  }
  async conflictToAttorney(request,actorId){const connection=this.connectionForWorkspace(request.workspaceId);const proposedSlots=connection?await this.proposedSlots(connection,{durationMinutes:request.state.consultation?.durationMinutes??30}):request.state.proposedSlots;const updated=await this.atlas.updateObject(request.workspaceId,request.id,{version:request.version,state:{...request.state,status:'slot_conflict_attorney_action',proposedSlots,calendarDelivery:delivery('pending','slot_no_longer_available')}},actorId);const options=proposedSlots.map((slot,index)=>`${index+1}) ${formatted(slot)}`).join('; ');await this.notifyAttorneyDirect(updated,{smsBody:`Atlas prevented a double booking for ${updated.state.prospectiveClient.name}. ${options}. Reply 1, 2, or 3 to send a replacement time.`});return updated;}
  async confirmClient(workspaceId,requestId,actorId){let request=await this.atlas.getObject(workspaceId,requestId);if(request.state?.status!=='awaiting_client_confirmation')throw new AtlasError('CONSULTATION_NOT_AWAITING_CLIENT','This consultation is not awaiting client confirmation',409);const selected=request.state.selectedSlot;if(!await this.slotAvailable(workspaceId,selected)){request=await this.conflictToAttorney(request,actorId,'The client confirmed, but the time became occupied before calendar publication.');return{request:publicRequest(request),calendarDelivery:request.state.calendarDelivery};}
    const now=this.clock();const jobs=await this.repository.listIntelligenceJobs(workspaceId);const sourceJob=[...jobs].reverse().find(job=>job.objectId===request.id);const proposal=await this.repository.createAiActionProposal({id:createId('aap'),workspaceId,runId:null,intelligenceJobId:sourceJob?.id??null,originType:'client_consultation_confirmation',proposedBy:request.state.targetUserId,actionType:'create_calendar_event',input:{title:`Prospective-client consultation — ${request.state.prospectiveClient.name}`,eventType:'scheduled_call',matterId:null,targetUserId:request.state.targetUserId,startsAt:selected.startsAt,endsAt:selected.endsAt,timeZone:selected.timeZone,attendees:[],description:`Website consultation request ${request.id}. Client confirmed the proposed time. Call ${request.state.prospectiveClient.number}.`,sourceType:'public_website_intake'},status:'pending',version:1,decidedBy:null,resultObjectId:null,createdAt:now,decidedAt:null});let calendar;try{calendar=await this.atlas.decideAiActionProposal(workspaceId,proposal.id,{version:1,decision:'approve'},request.state.targetUserId);}catch(error){if(error.code!=='CALENDAR_SLOT_CONFLICT')throw error;request=await this.conflictToAttorney(request,actorId,'The client confirmed, but another event claimed the time first.');return{request:publicRequest(request),calendarDelivery:request.state.calendarDelivery};}const when=formatted(selected);let clientSms=delivery('pending',calendar.calendarDelivery?.status==='published'?'sms_sender_not_configured':'calendar_not_published');let attorneySms=delivery('pending',calendar.calendarDelivery?.status==='published'?'sms_sender_not_configured':'calendar_not_published');if(calendar.calendarDelivery?.status==='published'&&this.clientSmsSender){try{const sent=await this.clientSmsSender({workspaceId,targetUserId:request.state.targetUserId,requestId:request.id,to:request.state.prospectiveClient.number,textConsent:true,authorizationType:'client_consultation_confirmation',body:`Florida’s Law Office: Your consultation is confirmed for ${when}. An attorney will contact you at ${request.state.prospectiveClient.number}. Reply STOP to opt out.`});clientSms=delivery(sent.message?.state?.status??sent.status??'sent',null,{provider:sent.message?.state?.provider??sent.provider??null,messageId:sent.message?.id??null});}catch(error){clientSms=delivery('pending',error.code??'SMS_DELIVERY_FAILED');}}
    if(calendar.calendarDelivery?.status==='published'&&this.attorneySmsSender){try{const sent=await this.attorneySmsSender({workspaceId,targetUserId:request.state.targetUserId,requestId:request.id,prospectiveClient:request.state.prospectiveClient,proposedSlots:[selected],timeZone:selected.timeZone,body:`Atlas: ${request.state.prospectiveClient.name} confirmed the consultation for ${when}. Call ${request.state.prospectiveClient.number}. The event is now on your connected calendar.`});attorneySms=delivery(sent.message?.state?.status??sent.status??'sent',null,{provider:sent.message?.state?.provider??sent.provider??null,messageId:sent.message?.id??null});}catch(error){attorneySms=delivery('pending',error.code??'SMS_DELIVERY_FAILED');}}
    request=await this.atlas.updateObject(workspaceId,request.id,{version:request.version,state:{...request.state,status:calendar.calendarDelivery?.status==='published'?'scheduled_confirmed':'client_confirmed_calendar_pending',clientConfirmedAt:now,calendarEventId:calendar.result.id,calendarDelivery:calendar.calendarDelivery,clientSmsDelivery:clientSms,attorneyFinalSmsDelivery:attorneySms}},actorId);return{request:publicRequest(request),calendarEvent:calendar.result,calendarDelivery:calendar.calendarDelivery,clientSmsDelivery:clientSms,attorneySmsDelivery:attorneySms};}
}
