const sessionKey='atlas-authenticated-session-v1';const $=id=>document.getElementById(id);let session=null;let siteObject=null;let site=null;let previewTimer=null;let activePageIndex=0;
function lines(value){return String(value??'').split(/\n+/).map(item=>item.trim()).filter(Boolean)}
function paragraphs(value){return String(value??'').split(/\n\s*\n/).map(item=>item.trim()).filter(Boolean)}
function storedSession(){try{return JSON.parse(sessionStorage.getItem(sessionKey)??'null')}catch{return null}}
async function refresh(){const response=await fetch('/v1/auth/refresh',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({refreshToken:session.refreshToken})});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??'Your Atlas session expired.');session.token=payload.data.accessToken;session.refreshToken=payload.data.refreshToken;sessionStorage.setItem(sessionKey,JSON.stringify(session));}
async function request(path,options={}){let response=await fetch(path,{...options,headers:{'content-type':'application/json',authorization:`Bearer ${session.token}`,...options.headers}});if(response.status===401&&session.refreshToken){await refresh();response=await fetch(path,{...options,headers:{'content-type':'application/json',authorization:`Bearer ${session.token}`,...options.headers}});}const payload=await response.json();if(!response.ok){const error=new Error(payload.error?.message??'Atlas could not complete the request.');error.details=payload.error?.details;throw error;}return payload.data;}
function currentPage(){return site.pages[activePageIndex]}
function bindIdentity(){const firm=site.firm;$('firmName').value=firm.name;$('firmShortName').value=firm.shortName;$('firmTagline').value=firm.tagline;$('firmPhone').value=firm.phone;$('firmEmail').value=firm.email;$('firmDomain').value=firm.domain;$('firmAddress').value=firm.addressLine1;$('firmCity').value=firm.city;$('firmRegion').value=firm.region;$('firmPostal').value=firm.postalCode;$('attorneyVerified').checked=firm.attorneyVerified;$('officeVerified').checked=firm.officeVerified;$('colorNavy').value=site.theme.navy;$('colorGold').value=site.theme.gold;$('colorCream').value=site.theme.cream;$('colorPaper').value=site.theme.paper}
function bindPages(selected=0){$('pageSelect').replaceChildren();site.pages.forEach((page,index)=>{const option=document.createElement('option');option.value=String(index);option.textContent=`${page.type} · ${page.navLabel}`;$('pageSelect').append(option)});activePageIndex=Math.min(selected,site.pages.length-1);$('pageSelect').value=String(activePageIndex);bindPage()}
function bindPage(){const page=currentPage();$('previewPageLabel').textContent=page.navLabel;$('pageNavLabel').value=page.navLabel;$('pagePath').value=page.path;$('pageSeoTitle').value=page.seoTitle;$('pageMeta').value=page.metaDescription;$('pageEyebrow').value=page.eyebrow;$('pageHeading').value=page.heading;$('pageSummary').value=page.summary;$('pageBody').value=page.body.join('\n\n');$('pageHighlights').value=page.highlights.join('\n');$('pageFaqs').value=JSON.stringify(page.faqs,null,2);$('pageAuthor').value=page.author;$('pageReviewedAt').value=page.reviewedAt;$('pageLocalEvidence').value=page.localEvidence.join('\n');$('pageLocalVerified').checked=page.localEvidenceVerified;$('localFields').classList.toggle('hidden',page.type!=='location');updateCounts();schedulePreview()}
function updateDraft(){const firm=site.firm;firm.name=$('firmName').value;firm.shortName=$('firmShortName').value;firm.tagline=$('firmTagline').value;firm.phone=$('firmPhone').value;firm.email=$('firmEmail').value;firm.domain=$('firmDomain').value;firm.addressLine1=$('firmAddress').value;firm.city=$('firmCity').value;firm.region=$('firmRegion').value;firm.postalCode=$('firmPostal').value;firm.attorneyVerified=$('attorneyVerified').checked;firm.officeVerified=$('officeVerified').checked;site.theme.navy=$('colorNavy').value;site.theme.gold=$('colorGold').value;site.theme.cream=$('colorCream').value;site.theme.paper=$('colorPaper').value;const page=currentPage();page.navLabel=$('pageNavLabel').value;page.path=$('pagePath').value;page.seoTitle=$('pageSeoTitle').value;page.metaDescription=$('pageMeta').value;page.eyebrow=$('pageEyebrow').value;page.heading=$('pageHeading').value;page.summary=$('pageSummary').value;page.body=paragraphs($('pageBody').value);page.highlights=lines($('pageHighlights').value);try{const faqs=JSON.parse($('pageFaqs').value);if(Array.isArray(faqs))page.faqs=faqs}catch{}page.author=$('pageAuthor').value;page.reviewedAt=$('pageReviewedAt').value;page.localEvidence=lines($('pageLocalEvidence').value);page.localEvidenceVerified=$('pageLocalVerified').checked;updateCounts()}
function updateCounts(){$('titleCount').textContent=`${$('pageSeoTitle').value.length}/65`;$('descriptionCount').textContent=`${$('pageMeta').value.length}/170`}
function schedulePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(()=>void preview(),180)}
async function preview(){if(!session||!site)return;updateDraft();$('builderStatus').textContent='Refreshing the server-rendered preview…';try{const result=await request(`/v1/workspaces/${encodeURIComponent(session.workspaceId)}/website-builder/preview`,{method:'POST',body:JSON.stringify({site,path:currentPage().path})});$('previewFrame').srcdoc=result.html;renderReadiness(result.readiness);$('builderStatus').textContent='Preview is server-rendered and remains noindex until release approval.';}catch(error){$('builderStatus').textContent=error.message;}}
function renderReadiness(readiness){$('readinessStatus').textContent=readiness.ready?'Ready for attorney release review':`${readiness.issues.length} item${readiness.issues.length===1?'':'s'} blocking release`;$('readinessStatus').className=readiness.ready?'ready':'blocked';const list=$('readinessIssues');list.replaceChildren();for(const issue of readiness.issues.slice(0,18)){const item=document.createElement('li');item.textContent=`${issue.path?`${issue.path} — `:''}${issue.message}`;list.append(item)}if(!readiness.issues.length){const item=document.createElement('li');item.textContent='Technical and content gates pass. Human approval and deployment checks are still required.';list.append(item)}}
async function save(){updateDraft();$('saveButton').disabled=true;$('builderStatus').textContent='Saving the canonical firm website record…';try{const path=siteObject?`/v1/workspaces/${encodeURIComponent(session.workspaceId)}/website-builder/sites/${encodeURIComponent(siteObject.id)}`:`/v1/workspaces/${encodeURIComponent(session.workspaceId)}/website-builder/sites`;siteObject=await request(path,{method:siteObject?'PATCH':'POST',body:JSON.stringify({site,id:siteObject?.id,version:siteObject?.version})});site=siteObject.state;$('builderStatus').textContent='Saved to the firm’s canonical Atlas workspace. The site has not been published.';await preview()}catch(error){$('builderStatus').textContent=error.message}finally{$('saveButton').disabled=false}}
async function prepareRelease(){if(!siteObject){await save();if(!siteObject)return}$('releaseButton').disabled=true;$('builderStatus').textContent='Checking identity, content, local evidence, metadata, and crawler controls…';try{const release=await request(`/v1/workspaces/${encodeURIComponent(session.workspaceId)}/website-builder/sites/${encodeURIComponent(siteObject.id)}/release-candidate`,{method:'POST',body:'{}'});$('builderStatus').textContent=`Release candidate ${release.id} is prepared for attorney review. Atlas has not published it.`;}catch(error){$('builderStatus').textContent=error.message;if(error.details?.issues)renderReadiness({ready:false,issues:error.details.issues})}finally{$('releaseButton').disabled=false}}
async function start(){session=storedSession();if(!session?.token||!session?.workspaceId){$('sessionWarning').textContent='Sign in to Atlas first, then open Website Builder again. The public template preview remains available at /website-preview/.';$('sessionWarning').classList.remove('hidden');$('builderForm').querySelectorAll('input,textarea,select,button').forEach(item=>item.disabled=true);$('builderStatus').textContent='No authenticated Atlas firm session is available.';return}try{const status=await request(`/v1/workspaces/${encodeURIComponent(session.workspaceId)}/website-builder`);siteObject=status.sites?.[0]??null;site=structuredClone(siteObject?.state??status.template);bindIdentity();bindPages();$('builderStatus').textContent=siteObject?'Loaded the firm’s saved website draft.':'Loaded the original criminal-defense template. Save when ready.';}catch(error){$('builderStatus').textContent=error.message}}
$('pageSelect').addEventListener('change',()=>{updateDraft();activePageIndex=Number($('pageSelect').value)||0;bindPage()});$('builderForm').addEventListener('input',()=>{updateDraft();schedulePreview()});$('builderForm').addEventListener('change',()=>{updateDraft();schedulePreview()});$('saveButton').addEventListener('click',()=>void save());$('releaseButton').addEventListener('click',()=>void prepareRelease());$('refreshPreview').addEventListener('click',()=>void preview());$('desktopPreview').addEventListener('click',()=>{$('previewFrameWrap').classList.remove('mobile');$('desktopPreview').classList.add('active');$('mobilePreview').classList.remove('active')});$('mobilePreview').addEventListener('click',()=>{$('previewFrameWrap').classList.add('mobile');$('mobilePreview').classList.add('active');$('desktopPreview').classList.remove('active')});void start();
